### ISSUE TITLE
add option to supply a list of regions instead of one at a time

### ISSUE THREAD

**Issue by malachig** [Illumina/strelka#1]
Instead of doing this in Strelka `--region chr2:100-2000 --region chr3:2500-3000` to limit the analysis to a region of the genome for debugging purposes, it would be nice if we could supply these regions in a file (e.g. in bed format).

Is there a reason why one should NOT do this. i.e. in a context other than for debugging purposes? For example, if we know in advance that we only care about variants in certain regions.

**Comment by ctsa** [comment]
Thanks for your interest -- as you point out the current `--region` option is really only designed to support debug and smoke-test scenarios. Our projects tend to emphasize WGS over WES and where we do analyze exome the shoulder calls can sometimes be of interest, thus we might typically call everything first and then apply a bed-file mask to the VCF.

I anticipate we'll be adding a bed-file based region selection option for both somatic and germline calling soon (by March 2017) -- this is more driven by requests to knock hg38 unplaced/decoy contigs out of the analysis but the feature should support exome/targeted analysis as well.

**Comment by malachig** [comment]
Thanks for the response @ctsa. 

I completely agree with your suggested approach.  Normally we take that strategy as well.  Our interest here is a bit of an edge case (but an important one). For our clinical pipeline we are interested in limiting analysis to only certain regions for performance reasons.  When producing data on the sequencing instrument it takes no extra time to cast a wide net and sequence a broad capture (e.g. entire exome).  However, when it comes to analysis, if we limit variant calling to only the regions we are going to report on, this can save run time.  In the case of strelka, for now we can probably just parallelize more to achieve our target run time.  But the `--region` option would still be a handy.  We will look forward to the update. :)

**Comment by ctsa** [comment]
Please see the new `--callRegions` option in the strelka 2.8.2 release here: https://github.com/Illumina/strelka/releases/tag/v2.8.2
