### ISSUE TITLE
which tier should be used to calculate variant allele frequencies

### ISSUE THREAD

**Issue by qindan2008** [Illumina/strelka#100]
Hi, 
Which tier should be used to calculate variant allele frequencies? only tier1, or depends on the value of TQSS_NT(or TQSS) ?  It's confused.
Thanks!

**Comment by sangtaekim** [comment]
We recommend to use only tier1 reads: https://github.com/Illumina/strelka/tree/v2.9.x/docs/userGuide#somatic-variant-allele-frequencies

**Comment by qindan2008** [comment]
OK, Thank you very much.
