### ISSUE TITLE
Pisces input limits

### ISSUE THREAD

**Issue by sbilobram** [Illumina/strelka#101]

**Comment by sbilobram** [comment]
We potentially would like to try Pisces in a project with low-coverage BAMs.   I do not find mention of input limits and only that minDepth default is at 10 and adjustable via parameter -c .
Is there a recommended Coverage for Pisces inputs (BAMs) ?  Minimum coverage?

**Comment by sangtaekim** [comment]
For questions related to Pisces, please use https://github.com/Illumina/Pisces/issues.
