### ISSUE TITLE
Finding consistent mutations between caccer and matched cancer model

### ISSUE THREAD

**Issue by beginner984** [Illumina/strelka#102]
Sorry you were right because when I tried with a pair of my RNA-seq .bam files I got results. Sorry please help me in getting intuition from these results; My ultimate goal is seeing whether mutations were
consistent between the tumor and the matched organoid, so I have a .vcf file for SNV and a .vcf file for indel, how I could know for instance CDKN2A has been mutated which samples (I mean cancer, organoid or both to find consistency)

Thank you for any help

_Originally posted by @beginner984 in https://github.com/Illumina/strelka/issues/99#issuecomment-471171746_

**Comment by sangtaekim** [comment]
Discussed in https://github.com/Illumina/strelka/issues/99.
