### ISSUE TITLE
impact of MANTA in SNVs ?

### ISSUE THREAD

**Issue by mortunco** [Illumina/strelka#103]
Hi, 

Just wanted to clarify this, our collaborators did not mention us about they used MANTA in their pipeline. We are only interested in **SNVs , no indels**. Do we have to analyse it from the beginning?

I know in the READme you mention about this I just wanted to double check it.

Thank you very much,

Tunc.

**Comment by sangtaekim** [comment]
We recommend to run Manta with Strelka only in somatic calling to improve sensitivity in detecting long (>10 bp) indels. For SNVs, the difference between `Strelka only` vs `Strelka+Manta` would be very small.

**Comment by mortunco** [comment]
thank you very much!
