### ISSUE TITLE
Could strelka get the other somtic snv?

### ISSUE THREAD

**Issue by ggoodstudydaydayup** [Illumina/strelka#104]
Hi,
    Could strelka get the other somtic snv , like 0/0 to 1/1 or 1/0 to 0/0 or other?  When I check my result, I found there were all snv, 0/0 to 1/0. I'm not sure because of my poor knowledge. If there were something wrong about my idea, please tell me.
    Thanks in advance.
Best,
Tom Liu

**Comment by sangtaekim** [comment]
What is the version of Strelka that you're using? Strelka somatic caller does not output FORMAT/GT. Instead it reports INFO/SGT (e.g. SGT=AA->AT).

**Comment by ggoodstudydaydayup** [comment]
1. The version is strelka-2.9.2. I just use the 0/0 for example not FORMAT/GT. Yeah, it reports INFO/SGT more 0/0 to 0/1 like AA ->AT. Less 0/1 to 0/0 like AT -> AA  with LowEVS.
2. Where could I change the default of EVS which is 7?
Thanks in advance!
Best,
Tom

**Comment by sangtaekim** [comment]
1. Detecting somatic variants where normal genotype is not homref is far more difficult and thus many existing variant callers (e.g. Mutect) don't report them. Strelka currently reports them as non-passing variants and we don't have a plan to change this behavior.  

2. You can do it by changing the "FilterCutoff" value in ``${STRELKA_INSTALL_DIR}/share/config/somaticSNVScoringModels.json``.

**Comment by ggoodstudydaydayup** [comment]
Thank you very much!
