### ISSUE TITLE
indel candidates from PINDEL

### ISSUE THREAD

**Issue by sjin09** [Illumina/strelka#110]
Dear @sangtaekim 

Thank you first for creating a great software for germline and somatic mutation detection. 

I was wondering if you have assessed indels from PINDEL as an alternative candidate for somatic INDEL detection. The pipeline in our institute uses PINDEL for INDEL calling and if PINDEL indel candidates is equal or better than MANTA indel candidates, I thought it would be better for me to run strelka2 with the PINDEL indel candidates.

Many thanks,
Sangjin Lee

**Comment by sangtaekim** [comment]
Hi Sangjin,

Adding Manta indel candidates is useful to call mid-size (e.g. 10-49) indels. We haven't compared PINDEL+Strelka and Manta+Strelka, but if PINDEL is good at calling mid-size indels, there is no reason you have to sitck to Manta.

Best,

Sangtae
