### ISSUE TITLE
Sample Names are Hard-coded

### ISSUE THREAD

**Issue by ellispatrick** [Illumina/strelka#111]
The somatic VCF column headings always have the samples named NORMAL and TUMOR. Another software I am using requires these sample IDs to match those specified by the user in that software and be different for each sample. Strelka2 doesn't provide any input parameters so that users could specify them, so it requires unsightly code such as

```
gunzip < VCFfile.gz | sed -e '0,/NORMAL/{s/NORMAL/SCC25normal/}' | sed -e '0,/NORMAL/{s/TUMOR/SCC25cancer/}' | gzip -c > temp.gz
mv temp.gz VCFfile.gz
```

May Strelka2 allow user-specified naming of samples, which would make it operate better with other software and make it much easier to do the basic task of putting multiple samples into a single VCF? For example, `bcftools merge` gives `Error: Duplicate sample names (NORMAL), use --force-samples to proceed anyway` on Strelka2 output somatic SNV VCF files. It would also make users' analysis scripts look neater if sed or awk hacks could be avoided.

**Comment by PedalheadPHX** [comment]
Agree this would be a nice feature, though I'd prefer it just used the RG_SM in the provided BAM files

**Comment by sangtaekim** [comment]
Hi @ellispatrick and @PedalheadPHX ,

Thanks for the suggestion, but since Strelka is not currently under active development, this change may not happen anytime soon.
