### ISSUE TITLE
calling de novo mutations from pedigree with multiple probands

### ISSUE THREAD

**Issue by sjin09** [Illumina/strelka#112]
To whom it may concern,

I am writing to request a feature. 

I have multiple pedigrees where there are multiple probands and I assume that denovo.py does not allow for multiple probands. I am not able to run denovo.py when the probands are separated by comma or space (--proband PD34276b,PD34277b or --proband PD34276b PD34277b).

I can, of course, run denovo.py on the individual probands independently adn combine the INFO tag, but I thought it would be convenient for other people if denovo.py could consider multiple probands.

Many thanks,
Sangjin Lee

**Comment by sangtaekim** [comment]
Dear Sangjin Lee,

Thanks for the suggestion, but we currently don't have a plan to change the denovo.py script. Please feel free to make your own version with the changes.

Best,

Sangtae
