### ISSUE TITLE
Number of variant bases at the position in the tumor sample

### ISSUE THREAD

**Issue by beginner984** [Illumina/strelka#114]
Hi,

I have called indel for a tumour and matched normal sample by strelka; In output, how I can locate the number variant bases for each position in tumour sample please?

This is link to my .vcf file

https://www.dropbox.com/s/lfn9greycjybnrt/_double_filtered_013_pre_indels.vcf?dl=0

**Comment by DarioS** [comment]
Unfortunately, Strelka does not determine the SVTYPE (e.g. INS or DEL) and SVLEN information about a variant. The fourth and fifth columns are REF and ALT which contain the DNA sequence of the reference (normal) and alternative (cancer) sample. You can calculate the number of characters in the fifth column and subtract from it the number of characters in the fourth column. If the number is negative, you have a deletion. If the number is positive, you have an insertion.

**Comment by sangtaekim** [comment]
Thanks @DarioS !
