### ISSUE TITLE
Somatic indel PASS in low coverage normal

### ISSUE THREAD

**Issue by abenjak** [Illumina/strelka#115]
Hi,
I ran Strelka 2.9.10 on a pair of normal and tumor samples, using the default parameters and the `--exome` option. Over 1,000 indels passed the default filters (FYI, Strelka1 "PASSed" only 15 indels in the same dataset).
It turns out that most of the passed indels have a very low coverage in normal (mostly less than 10, while the tumor was mostly 2-3 times more covered than the normal).
Disabling EVS produced only 120 indels that passed the filter. When compared to the EVS filtering, most of the indels that did not pass the "old filtering" had a _QSI_ref_ tag.
But disabling EVS is not recommended according to the manual, and indeed, most of the 120 indels that passed the "old filtering" had a _LowEVS_ when EVS was enabled. Intersection between the two filtering methods consisted of only 35 indels.
I would like to keep using the EVS, but I would prefer the _LowDepth_ to be more stringent, so that I don't need to use _ad hoc_ and rigid coverage cutoffs in downstream filtering. The current default minimum coverage in normal is only 3, which is too low IMHO (how reliable is a homozygous WT call if it's based on only few reads?). Can we change this threshold in the options?
Best,
Andrej

**Comment by sangtaekim** [comment]
Hi @abenjak , our intention for adding the LowDepth filter was to catch obviously wrong calls and we don't consider to change the default threshold defined at https://github.com/Illumina/strelka/blob/v2.9.x/src/c%2B%2B/lib/applications/strelka/strelka_shared.hh#L58. If needed, I recommend to change the source code and make your own build.

**Comment by abenjak** [comment]
Thank you @sangtaekim.
