### ISSUE TITLE
High snv numbers on strelka 2.8.0

### ISSUE THREAD

**Issue by mortunco** [Illumina/strelka#119]
Hi,

I am getting very high number of snvs from somatic mutation calling. Interestingly, when I compare strelka snv calls with the ICGC's snv calls (ICGC's consensus calls), some samples have ridiculous amount of difference.

So in one sample, ( only PASS ones were considered, only chromosomes chr1-22 x y m) 
ICGC consensus --> 3000 snvs
Strelka --> 4600000 snvs

I tried different filtration methods such as SomaticEVS, VAF (tumor alt allele/ (tumor ref allele+tumor alt allele ) and other strelka metrics but none of them consistently reduced the number of mutations. I also compared tumor/normal bam sizes. For this patient the ratio is 1.39 (So I think normal file has 30x coverage. I mean at the end of the day, these are ICGC's tissues so I think their quality is better than some threshold.)

I unfortunately couldnt use the most updates strelka version because of our two collaborators used specific versions of isaac + strelka to conduct their analysis. 

Here is my pipeline.
ICGC --> get mapped bam file.
bam --> samtools fastq --> get forward.fastq reverse.fastq
remap with Isaac4 
call germline mutations with Normal
call somatic mutations with Tumor with respect to Normal.

reference genome --> ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa

strelka 2.8.0
Isaac --> Version: Isaac-04.17.06.15
```
/groups/lackgrp/ICGC-Prostate/Reference-Files/strelka_build2.8.0/bin/configureStrelkaSomaticWorkflow.py --normalBam={input.normal} --tumorBam={input.tumor} --referenceFasta={reference_fasta} --runDir=analysis/patient/StrelkaSomaticWorkflow && 

analysis/patient/StrelkaSomaticWorkflow/runWorkflow.py -m local -j 25 --quiet && 

bcftools concat -O z -a analysis/{wildcards.patient}/StrelkaSomaticWorkflow/results/variants/somatic.snvs.vcf.gz analysis/{wildcards.patient}/StrelkaSomaticWorkflow/results/variants/somatic.indels.vcf.gz > {output}.vcf "
```

my strelka environment
```
name: strelka_environment
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=2.7.15
  - bcftools=1.8
  - openssl=1.0
```

Thank you very much for your help and time,

Best regards,

Tunc.

**Comment by sangtaekim** [comment]
The command looks okay but 4.6M somatic SNV calls are obviously wrong. Can you provide more details or share parts of the data?

**Comment by mortunco** [comment]
Sure. Should I send you like a chromosome ? what would you prefer? 

Thank you very much for your help!

**Comment by sangtaekim** [comment]
The smaller the better as long as I can reproduce the problem.

**Comment by mortunco** [comment]
Hi,

In this link, I shared tumor normal of chr19 of each samples.
https://www.dropbox.com/sh/dh0lp5thiq1206w/AADVtYNAzOo6FV-4r6B0Z1j4a?dl=0

I dont now how relavent but,

when i compare chr19 calls from whole genome. ( ran on whole genome and extracted chr19) the number of pass snvs are 54010

On the other hand, the pass ones on chr19 only snvs are 60780. Just so you know. 

Thank you very much for your help and following up this thread.

Best regards,

Tunc.

**Comment by sangtaekim** [comment]
Most of the passing SNVs are C->A and G->T mutations. It is likely to be a sample specific issue. Strelka could possibly remove some FFPE artifacts, but this tumor data looks to be beyond what it can control.

**Comment by mortunco** [comment]
hmm.. At them moment i am using QSS>60 filter. Do you think qss or somaticEVS can overcome this problem ?

In other words, which one I should use to increase confidence of my calls? QSS or SomaticEVS?

Thank you very much for your help,

T.

**Comment by sangtaekim** [comment]
QSS is unlikely to be able to suppress such artifacts. I would try to increase SomaticEVS thresholds using https://github.com/Illumina/strelka/blob/v2.9.x/scratch/util/reFilterSomaticVcf.py.

**Comment by mortunco** [comment]
thank you for your help. I will reopen if I still have questions regardingt his issue! :)
