### ISSUE TITLE
False negative mutation

### ISSUE THREAD

**Issue by damjanmk** [Illumina/strelka#120]
Hi,
I have two samples of a patient for whom we expect to find the BRAF c.1799T>A mutation since it is specified in a histopathology report (from real-time PCR). However, in the first sample Strelka finds the mutation but gives it a very low EVS = 0.4: `chr7    140753336       .       A       T       .       LowEVS  SOMATIC;QSS=1;TQSS=1;NT=ref;QSS_NT=1;TQSS_NT=1;SGT=AT->AT;DP=137;MQ=59.80;MQ0=0;ReadPosRankSum=0.22;SNVSB=0.00;SomaticEVS=0.40  DP:FDP:SDP:SUBDP:AU:CU:GU:TU    27:0:0:0:23,23:0,0:0,0:4,4      110:1:0:0:68,69:0,0:0,0:41,41`

In the second sample of the same patient, Strelka doesn't even find the mutation pre-filtering.

I am using Strelka 2.9.0. It is WES data so I am using the `--callRegions` and `--exome` arguments. These are the configuration parameters I am using
```
[StrelkaSomatic]
maxIndelSize = 49
depthFilterMultiple = 3.0
snvMaxFilteredBasecallFrac = 0.4
snvMaxSpanningDeletionFrac = 0.75
indelMaxWindowFilteredBasecallFrac = 0.3
ssnvPrior = 0.000001
sindelPrior = 0.000001
ssnvNoise  = 0.0000005
sindelNoiseFactor = 2.2
ssnvNoiseStrandBiasFrac = 0.5
minTier1Mapq = 20
minTier2Mapq = 5
ssnvQuality_LowerBound = 15
sindelQuality_LowerBound = 30
ssnvContamTolerance = 0.15
indelContamTolerance = 0.15
isWriteRealignedBam = 1
isSkipDepthFilters: 1
maxInputDepth: 10000
indelMaxRefRepeat: 8
indelMaxIntHpolLength: 14
sindelNoise: 0.000001
binSize: 25000000
extraVariantCallerArguments =
```

Do you know what might cause this result? 

Many thanks,
Damjan

**Comment by DarioS** [comment]
Because it is only one mutation, can you check how the reads around the genomic location look in IGV? The explanation could be as simple as the different pieces of cancer used for different assays contain different mutations. Cancer is heterogeneous and different samples of the same cancer may yield different results.

**Comment by sangtaekim** [comment]
Thanks @DarioS for the explanation. I'll close this ticket. Please reopen it or file a new ticket if there are additional questions.
