### ISSUE TITLE
strelka2 identify few LOH calls

### ISSUE THREAD

**Issue by qindan2008** [Illumina/strelka#121]
from raw strelka2 somatic calls, use  NT=="het" && QSS_NT >=15 or QSI_NT >=30 to get LOH variants, is it right ?  finally, I got much fewer LOH calls than somatic calls.

Thank you !

**Comment by sangtaekim** [comment]
Probably yes, you can get LOH calls using NT == "het" and QSS_NT >= threshold. However, since we do not test cases where NT != ref, I am unable to comment on its performance.

**Comment by qindan2008** [comment]
OK, thank you very much.
