### ISSUE TITLE
Demo configuration step failed

### ISSUE THREAD

**Issue by indapa** [Illumina/strelka#122]
I am trying to use Strelka2 for the first time. I tried running the somatic workflow demo:

`
**** Starting demo configuration and run.
**** Configuration cmd: 'python strelka-2.9.2.centos6_x86_64/bin/configureStrelkaSomaticWorkflow.py --tumorBam='strelka-2.9.2.centos6_x86_64/bin/../share/demo/strelka/data/NA12891_demo20.bam' --normalBam='strelka-2.9.2.centos6_x86_64/bin/../share/demo/strelka/data/NA12892_demo20.bam' --referenceFasta='strelka-2.9.2.centos6_x86_64/bin/../share/demo/strelka/data/demo20.fa' --callMemMb=1024 --exome --runDir=./strelkaSomaticDemoAnalysis'

/bin/sh: /mnt/wip/Software/strelka-2.9.2.centos6_x86_64/libexec/htsfile: Permission denied

CONFIGURATION ERROR:
Failed to pipe command: '"/mnt/wip/Software/strelka-2.9.2.centos6_x86_64/libexec/htsfile" -h "/mnt/wip/Software/strelka-2.9.2.centos6_x86_64/share/demo/strelka/data/NA12892_demo20.bam"'

It seem the binary htsfile is not executable, but when I chmod +x it, and run the command again I get the same error. Can you help point me in the right direction? 

Thank you for your help!

`

**Comment by sangtaekim** [comment]
This error seems to be related to your system. If the problem persists, please try to build it from the source code (https://github.com/Illumina/strelka/blob/v2.9.x/docs/userGuide/installation.md#build-procedure).

**Comment by sangtaekim** [comment]
I'll close the ticket. Please reopen if it turns out to be an issue with Strelka.
