### ISSUE TITLE
Problems with analysis of  paired  tumor-normal germline variants

### ISSUE THREAD

**Issue by qindan2008** [Illumina/strelka#124]
Run Strelka2 to find germline variants in paired tumor-normal samples.

python   /Software/strelka-2.9.10/bin/configureStrelkaGermlineWorkflow.py   \                                                                 
--exome   \
--config   /Software/strelka-2.9.10/bin/configureStrelkaGermlineWorkflow.py.ini   \
--callRegions     /Project/WES/SureSelect_Human_All_Exon_V6_r2/modified.padded.bed.gz  \
--bam   normal.sort.dedup.bam   \
--bam   tumor.sort.dedup.bam   \
--referenceFasta   /RefGenomes/human/ensembl_GRCh37.p13/genome.fa    \
--reportEVSFeatures

python   StrelkaGermlineWorkflow/runWorkflow.py    -m  local    -j   6

******** COMMAND-LINE ERROR:: EVS features can only be reported when analyzing a single sample ********

EVS features can not be reported, does this mean "Hard filter" couldn't be performed?  For example,  ConservativeGenotypeQuality and RelativeTotalLocusDepth  thresholds couldn't be used for filtering?

It will be perfect, if strelka2 can process germline, somatic and LOH variants at the same time, just like Varscan2.

**Comment by sangtaekim** [comment]
`--reportEVSFeatures` is mainly used for training EVS models. If you want to use EVS (which uses ConservativeGenotypeQuality and RelativeTotalLocusDepth as features), you just need to run Strelka without  `--reportEVSFeatures`. If you do not want to use EVS, you may run with `--disableEVS`. 

We are not actively adding new features to Strelka, so it is unlikely that a single Strelka run reports germline, somatic and LOH variants.

**Comment by qindan2008** [comment]
OK, I just want to get some EVS Features  for downstream filtering.
Thank you.
