### ISSUE TITLE
different sequencing types for normal and tumor

### ISSUE THREAD

**Issue by SebastianHollizeck** [Illumina/strelka#125]
Hi,
Is it possible to use mixed sequencing types for tumor and normal?

I have several samples of the same patient of different lesions sequenced as whole genome sequencing, just as the normal sample, however the diagnostic sample is "only" whole exome sequencing.
Can I still use the normal for paired somatic calling, or would the filters go crazy?

Cheers,
Sebastian

**Comment by sangtaekim** [comment]
Streka's somatic model assumes that tumor and normal samples are generated using the same sample prep and instrument. I think Strelka won't generate meaningful results for your WGS normal and WES tumor pair.

**Comment by SebastianHollizeck** [comment]
Thanks for the answer, that is what I suspected, as I got a very high number of variants from the exome  sequencing sample in comparison to the WGS samples.
That is a pity, but thank you for the confirmation.

I will have to resort to other variant caller for that case.
