### ISSUE TITLE
"Access Denied" when downloading in Silico Mixtures BAMs

### ISSUE THREAD

**Issue by gnarzisi** [Illumina/strelka#13]
For example 

https://s3.amazonaws.com/strelka-public/BAMs/InSilicoTumor1_Purity20.bam

returns:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>8C8AE62717A60010</RequestId>
<HostId>
5SKKH13Rnmq6Fodl1zp2/bXVgb6Ec/e7FFK/TMGIdFVjYI4g7jc+rm8VINYTfvbojl/KdobJqnM=
</HostId>
</Error>
```

The only BAM file that I can download is: 

https://s3.amazonaws.com/strelka-public/BAMs/InSilicoTumor1_Purity20.bam

**Comment by sangtaekim** [comment]
Thanks @gnarzisi for the report! Now all the files are made public. Can you try it now?

**Comment by gnarzisi** [comment]
Thanks. It works now. 
Having now the same issue with the vcf and bed files:

InSilicoMix_indels.vcf.gz InSilicoMix_indels.bed InSilicoMix_snvs.vcf.gz InSilicoMix_snvs.bed

**Comment by sangtaekim** [comment]
It should work now. Thanks again!

**Comment by gnarzisi** [comment]
Thank you for the quick fix!

**Comment by ctsa** [comment]
Thanks @gnarzisi and @sangtaekim . This appears to be resolved, please re-open if there are additional data access issues.
