### ISSUE TITLE
Mac OS catalina: could not install Strelka and run demos

### ISSUE THREAD

**Issue by hawkibo** [Illumina/strelka#164]
Hi, 
I tried to install Strelka in Mac OS catalina according to instructions and had problem with htslib, error file is attached below:

"

configure: error: in `/Users/-/-/strelka-2.9.10.release_src/build/redist/htslib-1.7-6-g6d2bfb7':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

"

I configure htslib manually and also installed htslib separately. Then it gives error with samtools and then I manually configure samtools but then it starts again with same htslib error. I could not solve and pass this step.

When I try to run demo files:

"/Users/-/strelkacentos/libexec/htsfile: cannot execute binary file
CONFIGURATION ERROR:
Failed to pipe command: '"/Users/-/strelkacentos/libexec/htsfile" -h "/Users/-/strelkacentos/share/demo/strelka/data/NA12891_demo20.bam"'
ERROR: Demo configuration step failed.   "

This time it is associated with htsfile. Mac OS could not use htsfile. 
How can I install Strelka and use it? Thanks.

**Comment by KatharineME** [comment]
I am experiencing this exact error. How did you resolve it @hawkibo ?

**Comment by hawkibo** [comment]
I think Catalina have some problems with compiling(same with other tools). You could try installing:
1. conda
2. script @serge2016 has written in issues 'problem to use boost version 1.72.0 #162'

**Comment by KatharineME** [comment]
Hi @hawkibo, thanks for the tip and the quick response.

I tried the solution in #162 and I ended up getting the same error that you originally noted above.

I have no problems installing and running Strelka on Linux, but installing Strelka on macOS is still elusive.

**Comment by hawkibo** [comment]
I could not compile/make/cmake with Catalina clang; so I have installed gcc/cmake with brew.
After downloading 'strelka-2.9.10.release_src.tar.bz2' and configuring build file as explained in the installation instructions, I made some changes in the Makefile and modified paths according to my brew gcc/cmake. Example:

SHELL = /bin/zsh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.18.4/bin/cmake       (normally it is something like /usr/local/bin/cmake...)

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.18.4/bin/cmake -E rm -f

Then I could be successful with 'make install' command and it is working with demos and other samples.
