### ISSUE TITLE
SAMPLE in multisample calling

### ISSUE THREAD

**Issue by colindaven** [Illumina/strelka#17]
Hi,

cheers for a professional package. I am testing the multisample variant calling on RNA-seq, which looks pretty decent.

However, one issue in the output file is the use of SAMPLE instead of the input filename/sample name. Can this be defined ìn the config file ? Or defaults(filenames) be used ? Anything has to be better than SAMPLE multiple times.

`#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE  SAMPLE  SAMPLE  SAMPLE  SAMPLE  SAMPLE  SAMPLE  SAMPLE`

Thanks,
Colin

**Comment by ctsa** [comment]
The sample field is supposed to be populated from the `@RG` record in each input BAM file header, and fall back to SAMPLE1, SAMPLE2, etc... if this cannot be found, as described here:

https://github.com/Illumina/strelka/tree/master/docs/userGuide#germline-vcf-sample-names

Can you confirm that this information is not in your BAMs? There may be at least one bug here with the default fallback not seqeuntially numbering "SAMPLE1, SAMPLE2" as documented, but it would also be concerning if the sample information is in the BAM header and we're not extracting this correctly.

**Comment by colindaven** [comment]
The information is not in the BAMs. What's interesting is that the fallback seems to be SAMPLE, not SAMPLE1..N.

I do not have any information in the `@RG` at present, but will include that for further use (this is RNA, not WGS, where my pipelines normally do not include `@RG`.

I will test the RG functionality in the future ... thanks

**Comment by ctsa** [comment]
Thanks for checking. I confirm the sample naming bug wrt SAMPLE vs. SAMPLE1..N, It is being tracked on #18 and should be fixed within a patch update or two.

**Comment by ctsa** [comment]
Also, @kscheffler / @felixschlesinger regarding using the RNA option for multiple samples at once, do we have any reason to believe this won't work well? I believe most of the RNA mode testing was on single samples.

**Comment by kscheffler** [comment]
All of the testing was on single samples, but I see no reason why the generalization to multi-sample would behave differently from the way it does for WGS.

**Comment by ctsa** [comment]
Hi @colindaven, The fix for this issue is now on master here: https://github.com/Illumina/strelka/commit/da8f18e8cf04c72a41d979746ae1c590e20d085e

It did not make it into the v2.8.4 release that we've just pushed up, but will be in the next point release.
