### ISSUE TITLE
Higher number of somatic variants on strelka2 vs strelka

### ISSUE THREAD

**Issue by ssrinis** [Illumina/strelka#19]
I am evaluating strelka2 vs strelka on tumor/normal pairs, and find that the number of missense variants called by strelka2 is almost 2x the number on strelka for the same samples. Is strelka2 more sensitive, and less specific than strelka? Is using a filter on SomaticEVS  recommended to filter out lower confidence variants? I noticed that "LowEVS" filters out variants with low SomaticEVS (< 6?), and was wondering if this could be changed to make it more stringent.

**Comment by ctsa** [comment]
Considering the entire `SomaticEVS` range, Strelka2 should have a favorable precision-recall curve compared to the same curve drawn from the original Strelka release using `QSS_NT`/`QSI_NT`. That said, it is true that the default PASS threshold point has been moved to call more aggressively based on the needs of our 'average' use-case. I realize this change may not be an ideal fit for all cases, or for simplifying the strelka vs strelka2 comparison based on single (precision,recall) point evaluation.

I created a quick utility script to change the filtration threshold in the current Strelka2 somatic VCF output here:

https://gist.github.com/ctsa/2abc1ddd2403185c8b44bc1ba8013f02

Using this script you should be able to refilter any Strelka2 VCFs to use a higher/lower SomaticEVS filtration threshold to simplify the comparison with Strelka.

We will add this to the the project's utility scripts collection (https://github.com/Illumina/strelka/tree/master/scratch/util) the next time master is updated.

**Comment by ssrinis** [comment]
Thank you! This is very helpful
