### ISSUE TITLE
starling2 segfault

### ISSUE THREAD

**Issue by przemekl** [Illumina/strelka#2]
I have repetitive problem with strelka/starling2.
Workflow executed independently on two different machines, fails during processing the same area of chromosome 21 (log fragment below). Bam file has been processed by latest version of Isaac.
What could be causing these problems?
[strelka_error_selected.txt](https://github.com/Illumina/strelka/files/876472/strelka_error_selected.txt)

**Comment by sangtaekim** [comment]
Thanks for the report! Can you share the pyflow_tasks_stderr_log.txt at workspace/pyflow.data/logs? It would also be great if you can share the bamlet around the problematic region.

**Comment by przemekl** [comment]
It turned out to be linking/local libraries problem. Thanks for helping me.

**Comment by bingreily** [comment]
> It turned out to be linking/local libraries problem. Thanks for helping me.

Hi I'm facing the same problem in a different chromosome. May I ask how you were able to solve this?
What kind of local library problem was it?
