### ISSUE TITLE
--callRegions for WGS - run in parallel for i.e. each Chromosome

### ISSUE THREAD

**Issue by FriederikeHanssen** [Illumina/strelka#206]
Thank you for providing this tool. I have searched the issues and docmentaiton but couldn't find an answer to my question. So apologies if that is already answered elsewhere and I missed it.

Is it possible to run Strelka2 (v 2.9.10) in parallel for each region for one patient, such as one run for chr1, one for chr2 and so on and merge the resulting vcfs in the end?

Thank you :)

**Comment by sagitaninta** [comment]
I think this is what already happen when you run `${runningDirectory}/runWorkflow.py -m local -j 20`. See https://github.com/Illumina/strelka/blob/v2.9.x/docs/userGuide/README.md#execution

Hope this helps.

**Comment by FriederikeHanssen** [comment]
somewhat, yes.
