### ISSUE TITLE
Detecting indels > 50 bases in length

### ISSUE THREAD

**Issue by mozack** [Illumina/strelka#21]
From the user guide:
"Strelka is capable of detecting SNVs and indels up to a predefined maximum size, currently defaulting to 50 bases or less. "

Is there a way to increase the default limit of 50?

**Comment by ctsa** [comment]
Sorry, I realize we put this into the user configuration for manta, but not for strelka, so the code does not match the documentation. We have a fix going in now which should appear in the next patch release.

**Comment by ctsa** [comment]
Also I would separately note - the detection and genotyping methods in strelka are not well parameterized or tested for indels larger than 50 bases. I would strongly recommend our SV/large indel caller (manta) for larger indels instead:

https://github.com/Illumina/manta

**Comment by mozack** [comment]
OK thanks.  Will try both.  Is there an estimated timeframe for the next patch release?

**Comment by ctsa** [comment]
It's hard to project exactly as we are still trying to wrap up a few other items. If it helps I've pushed the max indel size config change up to a preview branch here:

https://github.com/Illumina/strelka/tree/issue21Preview

**Comment by mozack** [comment]
I don't appear to see a difference in results when using the preview branch.  However, running in conjunction with Manta appears to have the desired effect.  Will go with that instead.

**Comment by ctsa** [comment]
Glad to hear you could work around this issue with manta. The configuration fix previewed above is now part of today's v2.9.0 release.
