### ISSUE TITLE
error about genome size and bad lexical cast when using a reference genome larger than 2^32

### ISSUE THREAD

**Issue by JingzhX** [Illumina/strelka#22]
I installed strelka and test the demo script without any problem, and run on my own several human genome sequencing data successfully. But when I use strelka in wheat genome (15Gbp in size), the job always failed because the following error:

`[2017-11-14T02:27:54.171311] [Memmery01] [21053_1] [WorkflowRunner] [ERROR] [2017-11-14T02:27:01.344216] [Memmery01] [21053_1] [CallGenome+callGenomeSegment_chromId_000_chr1A_part1_0002] ******** COMMAND-LINE ERROR:: argument after flag -genome-size (10323499860) cannot be parsed to expected type: bad lexical cast: source type value could not be interpreted as target ********`

Then I tried to run on each chromosome individually (independent fasta file and bam file), and no problem exist. 

Any solution to this issue?
Thanks very much.
Jingzhong

**Comment by ctsa** [comment]
Very interesting case which we have not considered so far. I can't suggest any solutions from user configuration options alone, but the fix to the code should be straightforward in theory. We will try to get this into the next patch update and add a notification on this issue.

**Comment by ctsa** [comment]
Sorry for the delay. This issue described here should be resolved in today's v2.9.0 release.
