### ISSUE TITLE
Error running demo germline data

### ISSUE THREAD

**Issue by dietmarfdz** [Illumina/strelka#23]
I installed the software and I was able to run the demo data for the somatic version with no errors. When I tried to run it  for the germline version I got an error.

Attached you can find the error log file reported.

[workflow.error.log.txt](https://github.com/Illumina/strelka/files/1477761/workflow.error.log.txt)

**Comment by ctsa** [comment]
The demo is attempting to run the following bash command at the very end of the workflow:

    ln -s "genome.S1.vcf.gz" "genome.vcf.gz" && ln -s "genome.S1.vcf.gz.tbi" "genome.vcf.gz.tbi"'

This is failing and returning the following error message:

    ln: failed to create symbolic link 'genome.vcf.gz': Operation not supported

Perhaps this is a permission issue? I'm not familiar with settings that would specifically exclude soft-linking. If we could detect this, we could try to add a workaround.

**Comment by dietmarfdz** [comment]
Hi,

You were right it was a problem of privileges... I fixed it and it already worked.

Thanks
