### ISSUE TITLE
Confusing version numbers (strelka "1")

### ISSUE THREAD

**Issue by smondet** [Illumina/strelka#26]
Hi

When downloading the tar.gz from ftp://ftp.illumina.com/v1-branch/v1.0.14/ we get a `strelka_workflow-1.0.14` directory with

```
 $ cat version.txt 
1.0.14
```

But then the "main" c++ file is called `strelka/src/bin/strelka2.cpp` and in `strelka/src/lib/strelka/strelka_info.hh`:

```
    const char* version() const {
        static const char VERSION[] = "2.0.17.strelka1";
        return VERSION;
    }
```

What does all this mean?

Thanks

CC: @julia326

**Comment by ctsa** [comment]
It is confusing. Strelka1 was managed in two code repositories -- one for the actual binary and one for the perl/make wrapper "workflow". The workflow version, in this case "1.0.14", is the only one intended for use.

All recent Strelka2 releases have a new integrated workflow as part of a single code repo with a more easily identified version numbering scheme.

**Comment by ctsa** [comment]
I'll go ahead and close this as answered. Please reopen if further discussion would help.
