### ISSUE TITLE
Unknown htslib error value in sam_read1

### ISSUE THREAD

**Issue by lw3259111** [Illumina/strelka#27]
I have three sample,(A,B,C). after aligned, A,with B is well ,but C with B ouput some error, in below:  

[ERROR] [2018-01-04T12:30:20.971184] [localhost.localdomain] [15578_1] [CallGenome+callGenomeSegment_chromId_011_Chr12_0000] FATAL_ERROR: strelka EXCEPTION: ERROR: Unknown htslib error value in sam_read1 '-2' while attempting to read BAM/CRAM file:

**Comment by ctsa** [comment]
Thanks for reporting this -- is it reproducible? We've (very rarely) seen similar I/O failures but these appear to be sporadic hardware issues.

**Comment by lw3259111** [comment]
@ctsa  Yes, i will repeat the sample. Thanks.
