### ISSUE TITLE
Too many somatic mutations in the vcf output

### ISSUE THREAD

**Issue by snoopy-448** [Illumina/strelka#3]
HI
I want to use Strelka to call somatic snvs and indels for my WGS data. I have called somatic snvs by Mutect, there are ~8000 somatic snvs.
However, there is about 100,000 indels in the results/variants/somatic.indel.vcf and about 150,000 snvs in the results/variants/somatic.snv.vcf. Obviously, the somatic mutations are too too many. As the workflow is easy (I have to say it is the most convenient and user-friendiness software I have used, THANKS!), I think my command line should not be wrong. So, I think there must be some filtering things I have not done for the final results. I saw at this page （https://sites.google.com/site/strelkasomaticvariantcaller/home/somatic-variant-output）that there is an all.somatic.vcf and pass.somatic.vcf in the variants directory, I wonder if my output vcf with so many somatic mutations is the all.somatic.vcf. But I cannot find the pass.somatic.vcf. Could you give me some advice?
Thanks a lot!
Yang

**Comment by ctsa** [comment]
A few things have changed from strelka1 to strelka2, and one of these is that we stopped providing two separate all/pass files for each variant type. For help with strelka2, please see the in-source markdown documentation, for instance the user guide here:

https://github.com/Illumina/strelka/tree/master/docs/userGuide

...is a good starting point and there's a brief note about the somatic output files in particular here:

https://github.com/Illumina/strelka/tree/master/docs/userGuide#somatic

The current somatic output file contains all variants (as you have observed). Our recommended filtration is noted in the FILTER field -- please use the variants with a FILTER value set to PASS as the starting point for your analysis and adjust to more liberal/conservative filtration thresholds from there.

Note we will be updating this site with our 2.8.0 release within the next several weeks, for which you should expect further improvements to the somatic indel model.

**Comment by snoopy-448** [comment]
Thanks for so quick answering! 
I have another simple question about the output format. I want to calculate the variant allele frequency of a somatic indel, and I have two choices:
vaf_1 = first number of TIR / DP
vaf_2 = second number of TIR / DP2
for different standards.
Is my understanding right?
Thanks!

**Comment by ctsa** [comment]
Somatic indel indel allele frequency is: alt_t1count / (ref_t1count + alt_t1count)

...where:

ref_counts = value of FORMAT column value “TAR”
alt_counts = value of FORMAT column value “TIR”
ref_t1count = $ref_counts[0] (use the tier1 counts -- the first value in the comma-delimited list)
alt_t1count = $alt_counts[0] (...likewise..)

**Comment by IraDeveson** [comment]
This is very helpful, as I was having some trouble interpreting the FORMAT field precisely. Could you please provide similar instructions with which one can calculate Variant Allele Fraction for Somatic SNVs?

Greatly appreciated

**Comment by student-t** [comment]
The VCF standard is to make "AF" field in the VCF file. This is very common and useful for somatic analysis. @ctsa Do you think you can provide a new update with the field filled-in? It shouldn't be hard.

**Comment by ctsa** [comment]
@IraDeveson  - We will add a section to the user guide for the upcoming 2.8.0 release.
@student-t - "AF" is perhaps too easily confused with its population allele frequency usage, the likely trajectory is to move towards the more standard `AD` counts, which will make the corresponding allele frequency simpler to extract.

**Comment by igordot** [comment]
I got to this thread while trying to figure out the allele frequencies output. As mentioned earlier:

> ref_counts = value of FORMAT column value “TAR”
> alt_counts = value of FORMAT column value “TIR”

I am a little confused why TAR is "reads strongly supporting alternate allele", but it's actually the reference allele. What is the difference between "alternate allele" and "indel allele"?

**Comment by ctsa** [comment]
@IraDeveson - recently added to user guide here: https://github.com/Illumina/strelka/blob/master/docs/userGuide/README.md#somatic

**Comment by ctsa** [comment]
@igordot - It's a poor choice of words, but here "alternate" means all alleles at the same locus other than the somatic indel in question. Please open a new issue to discuss further.
