### ISSUE TITLE
Detect mosaic with strelka?

### ISSUE THREAD

**Issue by dietmarfdz** [Illumina/strelka#34]
Hi!

Is it possible to detect mosaic events with strelka2?

**Comment by ctsa** [comment]
There is not well tested mosaic support, but strelka does include a feature to redefine the model for a heterozygous variant from 0.5 to a variant frequency range covering 0.5 +/- X. This was written to account for allele specific expression in RNA-Seq data, but should help to recover low-frequency mosaic events as well.

To use this option, you need to edit the strelka config file, and add the option `--het-variant-frequency-extension X` to the `extraVariantCallerArguments` key, where "X" sets the het variant frequency range to "0.5 +/- X". For instance to treat all frequencies from 0.05 to 0.95 as heterzygous calls, you can modify the strelka germline config file to read:

```
extraVariantCallerArguments = --het-variant-frequency-extension 0.45
```

**Comment by dietmarfdz** [comment]
First of all, thank you for your answer. I tried two things but none of them worked. Could you please give a me clue?

1) I tried to add the option you explained in the step for generating the config file:

`$/configureStrelkaGermlineWorkflow.py --bam $/file1.bam  --referenceFasta $hs37d5.fa extraVariantCallerArguments = --het-variant-frequency-extension 0.35 --exome --callRegions $sure50mb.bed.gz --runDir $/test`

an I got the following:

**configureStrelkaGermlineWorkflow.py: error: no such option: --het-variant-frequency-extension**

2) I also went to the "configureStrelkaGermlineWorkflow.py" file just in case there was inside an option for  extraVariantCallerArguments but there was none.

**Comment by dietmarfdz** [comment]
First of all thank you for your answer. I added the code to the strelka germline config file as you recommended and when executing the runWorkflow.py I got among others, the following error:

`[2018-02-21T15:59:27.449772] [isg] [53444_1] [TaskManager] [ERROR] [2018-02-21T15:59:25.994825] [isg] [53444_1] [CallGenome+callGenomeSegment_chromId_000_1_0001] ******** COMMAND-LINE ERROR:: Invalid argument: --het-variant-frequency-extension ********`

In the following link you can download the workflow.error.log.txt file. (I just deleted some paths of the file but esentially the file does not change.)

I attach you also the configureStrelkaGermlineWorkflow.py.ini file so that you can check the change I performed.

https://drive.google.com/drive/folders/11wuqmNLIe2uHLEUaKzH-SGF1ud8GLbC7?usp=sharing

Just to notice, when I analyze the same sample without adding the code you gave me, it worked perfectly.

Thanks in advance

**Comment by ctsa** [comment]
Sorry it looks like  the option name changed from v2.8.4 to v2.9.0. You could either retry this command with v2.9.0 (recommended because v2.9.0 makes a number of other improvements) -- or in v2.8.4 and below you can use `-bsnp-diploid-het-bias` instead of `--het-variant-frequency-extension`. Note that the use of a single - and double -- between the two suggestions is not a typo.

**Comment by dietmarfdz** [comment]
Perfect it worked!!!
