### ISSUE TITLE
Filtering variants

### ISSUE THREAD

**Issue by dietmarfdz** [Illumina/strelka#35]
When analyzing the sample (for looking mosaic), I get for an exome sample (exome option included) more or less 40000 variants when filtering for just taking the "PASS" flag. Anyway, that´s too much. I would like to get around 10 variants per sample. Could you please recommend some other filters to apply to the variants.vcf result file?

Thanks in advance

**Comment by ctsa** [comment]
I assume from the previous ticket discussion you are also using the options we discussed to redefine the frequency range of a heterozygous call?

If so, this would explain why you're seeing a large number of passed calls (and if not the rest of this discussion will not be applicable). The `--het-variant-frequency-extension` is a fairly simple approach in that we're looking for "mosaic" variant frequencies by considering one possible variant at a time. You can sharpen the search for these cases by (1) start by searching for mosaic CNVs, for which you should have more power (2) look for candidates showing up using the standard heterozygous variant model (3)  look at new candidates introduced by the `--het-variant-frequency-extension` option after annotation and/or with a lower frequency range than discussed on the previous ticket (we discussed setting it to 0.45 to look over the frequency range of 5%-95% frequency, which is going to be very aggressive.

Finally note that the above option was written to address ASE in RNA-Seq data, so should be helpful for mosaic variant detection but not optimized for this case. Other tools have added some new options more specifically focused on this use case -- a good way to review some of these options is to look at the pipelines submitted for the PrecisionFDA hidden treasures challenge.
