### ISSUE TITLE
Assertion `callRegion.end > callRegion.begin' failed

### ISSUE THREAD

**Issue by BenoitFiset** [Illumina/strelka#36]
Hello,

where would I start to debug this error ?

The call is:

$STRELKA_DIR/configureStrelkaSomaticWorkflow.py \
--targeted \
--normalBam $STRELKA_BAM_CONTROL \
--tumorBam $STRELKA_BAM_TUMOR_DIR_P1/$STRELKA_INPUT/$STRELKA_BAM_TUMOR_DIR_P2 \
--referenceFasta $STRELKA_FASTA \
--callRegions $STRELKA_CALL_REGION \
--runDir ./${STRELKA_INPUT}_${STRELKA_OUTPUT_DIR}

So this  is a somatic call, using a --callRegion bed file. The region bed file is built to only have Exon locations in GRCh38 v91. (bgzip and tabix processed). This file was build from something like this: http://crazyhottommy.blogspot.ca/2013/05/find-exons-introns-and-intergenic.html

From the pyflowTaskWrapper.signal.txt error file:
 [2018-03-13T21:55:38.141622] [cp2329.m] [15635_1] [WorkflowRunner] [ERROR] [CallGenome+callGenomeSegment_chromId_002_11_0008] [taskWrapper-stderr] [2018-03-13T20:30:01.442615] [cp2329.m] [15635_1] [CallGenome+callGenomeSegment_chromId_002_11_0008] strelka2: /builder/src/c++/lib/starling_common/starling_pos_processor_util.cpp:104: void getSubRegionsFromBedTrack(const string&, const string&, const known_pos_range2&, std::vector<known_pos_range2>&): Assertion `callRegion.end > callRegion.begin' failed.
[2018-03-13T21:55:58.998848] [cp2329.m] [15635_1] [WorkflowRunner] [ERROR] Failed to complete sub-workflow task: 'CallGenome' launched from master workflow, failed sub-workflow classname: 'CallWorkflow'

Any help would be appreciated,

Thanks,

B.

**Comment by ctsa** [comment]
Sorry, I've noted to replace that assertion with a detailed exception message.

The assertion indicates that the bed file contains at least one zero- or negative-size region. Is this something you're expecting?

**Comment by BenoitFiset** [comment]
You mean that in the bed file there is a region that the end coord is smaller then the start coord ?

I'll validate, but doubt it unless mergeBed does something bad...

Is there somewhere in the logs a place that can at least point me in a region in the bed file ? With the error callGenomeSegment_chromId_002_11_0008  I guess Chromosome 11, but which entry in the bed file that is problematic would help.

Thanks for insight...

B.

**Comment by ctsa** [comment]
You can extract the corresponding command-line to this task as follows:

    cat ${STRELKA_RUN_DIR}/workspace/pyflow.data/state/pyflow_tasks_info.txt | awk '$1 == "callGenomeSegment_chromId_002_11_000"'

This should return a single record containing the task command-line, within which you should be able to search for `--region <arg>`, where `<arg>` is a standard samtools region string.

Going forward, the new exception message appearing in our next release will provide chromosome region and point the the exact bed line if this occurs again.

**Comment by BenoitFiset** [comment]
Was missing a 8 at the end of the command

cat ${STRELKA_RUN_DIR}/workspace/pyflow.data/state/pyflow_tasks_info.txt | awk '$1 == "callGenomeSegment_chromId_002_11_0008"'

Found the record have this : --region 11:90057751-101314968

So be certain I understand, In my created BED file, I should look for something wrong between those 2 coordinates ?

You wand me to test your patch and see your exception message works ?

Thanks.

**Comment by BenoitFiset** [comment]
Ok, here is what I found I finally did have a 0 length region if I subtract the end and start positions.
The exon line in my BED file is: "11  101050949  101050949"

Which is a valid entry in the Ensembl GRCh38 v91 gtf file:
11	ensembl	exon	101050949	101050949	.	-	.	gene_id "ENSG00000082175";

I'm running the execution of my bed file without this region.... won't know the results before X hours.

My question, If this works, how does your code validate this BED entry toward the region that is being processed ? An exon of length 1 (this case the exact position of 101050949) should not be seen as 0 length. 

Your error message "Assertion `callRegion.end > callRegion.begin' ", the code behind it for it not flag a region like this...  The region is good if:  `callRegion.end >= callRegion.begin' ?

Thanks I'll keep you posted.

Thanks.

**Comment by ctsa** [comment]
Thanks for the additional detail. Two new points:

## GTF to BED conversion

1. It looks like the GTF to BED conversion is incorrect. GTF is documented as having a 1-indexed start and end field, so the translation of the single base exon:

    11	ensembl	exon	101050949	101050949	.	-	.	gene_id "ENSG00000082175";

should be BED record:

    11 101050948 101050949

As quoted in your comments above, it is being translated into a zero-length record, and probably all of your exons are being converted to 1 minus the intended size.

## Strelka BED record policy

In final testing of the strelka assertion to exceptoin change, it looks like we have an inconsistent policy. Negative sized BED regions are just being ignored, and only zero-length records are actually being flagged as a QC failure. I'm discussing now whether we want to push all region lengths <= 0 to be ignored or to trigger an exception.

**Comment by BenoitFiset** [comment]
Thanks for the insight. 

Didn't notice the code on: http://crazyhottommy.blogspot.ca/2013/05/find-exons-introns-and-intergenic.html to convert GTF to BED had a bug in the awk code in the first step converting GTF from 1-based (and inclusive on both sides of the interval) to BED  0-based (and non-inclusive on the right).

The code should be: 
    `awk 'BEGIN{OFS="\t";} $3=="exon" {print $1,$4-1,$5}'`

And not:
    `awk 'BEGIN{OFS="\t";} $3=="exon" {print $1,$4,$5}'`

So new bed file is now right - 0-Based... The offending line in the BED file is now:
`11	101050948	101050949`

I'll keep you posted on the outcome of the run. My guess it should be fine.

Thanks.

**Comment by BenoitFiset** [comment]
[WorkflowRunner] Strelka somatic workflow successfully completed.
[WorkflowRunner] 
[WorkflowRunner]  workflow version: 2.9.0
[WorkflowRunner] 
[WorkflowRunner] Workflow successfully completed all tasks
[WorkflowRunner] Elapsed time for full workflow: 23174 sec

**Comment by ctsa** [comment]
Invalid bed record check improved to consistently trigger and provide a more detailed exception message indicating the problematic record -- change is now on master.

**Comment by BenoitFiset** [comment]
Thanks for the update.
