### ISSUE TITLE
big genome problem

### ISSUE THREAD

**Issue by lw3259111** [Illumina/strelka#39]
I have used isaac4 to assemble my reads with big genome, but i can't successfully annotation my bam with a big genome with strelka.
So,could you help me to solve the problem?

**Comment by lw3259111** [comment]
```
ErrorParams+Sample000+countErrors_chromId_008_chr5H_consensus_0162] ******** COMMAND-LINE ERROR:: argument after flag -genome-size (4450812722) cannot be parsed to expected type: bad lexical cast: source type value could not be interpreted as target ********
```
The error information as shown in the here.

**Comment by ctsa** [comment]
The issue described above should be removed in v2.9.0+, our most recent release is v2.9.2 available here:

https://github.com/Illumina/strelka/releases/tag/v2.9.2

Please let us know if you still have problems with the newer version.

**Comment by ctsa** [comment]
Thanks for the update, good to hear.
