### ISSUE TITLE
demo directory not present with conda installation

### ISSUE THREAD

**Issue by komalsrathi** [Illumina/strelka#41]
Hi,

I am trying to install Strelka using conda: 

```
$ conda install -c bioconda strelka

$ bash runStrelkaSomaticWorkflowDemo.bash

**** Starting demo configuration and run.
**** Configuration cmd: './configureStrelkaSomaticWorkflow.py --tumorBam='./../share/demo/strelka/data/NA12891_demo20.bam' --normalBam='./../share/demo/strelka/data/NA12892_demo20.bam' --referenceFasta='./../share/demo/strelka/data/demo20.fa' --callMemMb=1024 --exome --runDir=./strelkaSomaticDemoAnalysis'

Usage: configureStrelkaSomaticWorkflow.py [options]

configureStrelkaSomaticWorkflow.py: error: Can't find reference fasta file: '/mnt/isilon/cbmi/variome/rathik/tools/miniconda3/envs/mut-env/share/demo/strelka/data/demo20.fa'

ERROR: Demo configuration step failed
```

But there is no demo directory under share:

```
ls /mnt/isilon/cbmi/variome/rathik/tools/miniconda3/envs/mut-env/share/

doc  info  man  readline  strelka-2.9.2-0  tabset  terminfo
```

Thanks!!

**Comment by sangtaekim** [comment]
Thanks for the report. Indeed, the bioconda recipe for Strelka removes demo files (https://github.com/bioconda/bioconda-recipes/blob/84def6696d9b98b1b314dab86abfa008a5d14fda/recipes/strelka/build.sh#L9). We will consider to update bioconda with a demo in a future release.

**Comment by ctsa** [comment]
@sangtaekim - if adding the demo is complicated, perhaps we could at least remove the demo run scripts in conda?

**Comment by sangtaekim** [comment]
Sorry for the delay. I've updated the bioconda recipe to include demo files. It still sits in my local repo. I'll push the recipe right after we release 2.9.4 (hopefully within 10 days).

**Comment by sangtaekim** [comment]
The bioconda recipe has been updated. I've verified that the demo/verification successfully completes. Closing the ticket.
