### ISSUE TITLE
about proper pair filtering in strelka2

### ISSUE THREAD

**Issue by ShannonDaddy** [Illumina/strelka#43]
continue from #40 

Hi, chris

I checked these sam records again, but I found that the sam flags of them are 99 or 147, which mean they are proper paired. Does streka check 'proper paired' from the sam flags or somewhere else?

cons:168234 99 chr7 55242432 60 100M = 55242432 100 GGGTGAGAAAGTTAAAATTCCCGTCGC
 cons:168234 147 chr7 55242432 60 100M = 55242432 -100 GGGTGAGAAAGTTAAAATTCCCGTCGC
 cons:168235 99 chr7 55242432 60 100M = 55242432 100 TGGTGNGAAAGTTAAAATTCCCGTCGC
 cons:168235 147 chr7 55242432 60 100M = 55242432 -100 TGGTGNGAAAGTTAAAATTCCCGTCGC
 cons:168236 99 chr7 55242432 60 33M15D52M15S = 55242433 100 TGGTGNGAANGTTAAAATT
 cons:168236 147 chr7 55242433 60 16S32M15D52M = 55242432 -100 CTATCAATCCAATACTGGT
 cons:168237 99 chr7 55242432 60 33M15D52M15S = 55242433 100 TGGNGAGAAAGTTAAAATT
 cons:168237 147 chr7 55242433 60 16S32M15D52M = 55242432 -100 CTAACAACCAACCCCTGGT

**Comment by ctsa** [comment]
This is correct -- it is not the proper pair flag. I took a more detailed look at your example and the issue still pertains to amplicon not being as well supported: strelka will unroll soft-clipping while scoring indels, and this leads to trouble with the soft-clipped adapter sequence for the reads supporting the indel. Unfortunately we don't have a runtime option to switch this off right now, if you really wanted to the line:

https://github.com/Illumina/strelka/blob/105d8371f84018750eaaff6e205e3de1dbd6dfdd/src/c%2B%2B/lib/starling_common/starling_read_align.cpp#L2053

...could be commented out and strelka could be recompiled. When that change is made the indel is called in the output as follows:

    chr7    55242464        .       AGGAATTAAGAGAAGC        A       .       PASS    SOMATIC;QSI=796;TQSI=1;NT=ref;QSI_NT=3070;TQSI_NT=1;SGT=ref->het;MQ=60.00;MQ0=0;RU=GGAATTAAGAGAAGC;RC=1;IC=0;IHP=3;SomaticEVS=11.68     DP:DP2:TAR:TIR:TOR:DP50:FDP50:SUBDP50:BCN50   1932:1932:1932,1932:0,0:0,0:1583.59:17.27:0.00:0.01     2944:2944:2640,2640:304,304:0,0:2411.40:14.70:0.00:0.0
