### ISSUE TITLE
different result after cut primers

### ISSUE THREAD

**Issue by ray1919** [Illumina/strelka#44]
I call forcedGT using strelka. 

The first try, I only cut adapters from reads, the given snp is called correctly. 

The second try, I cut the 5p/3p primers in read1 and read2, however, the result tells that LowGQX, with depth only 4, the first call depth is  37877. 

I viewed the bam alignment using IGV, the alignment is just right there, why does strelka give such different result?

this snp is not the only one, I have see many snp had such problem

**Comment by ctsa** [comment]
Hi @ray1919, I'm inferring from the above details that this is amplicon data? If so, there are many amplicon specific optimizations and testing that are not strongly supported in strelka. Can I recommend you have a look at https://github.com/Illumina/Pisces for this purpose?

If you send additional details on the above issue we can try to help. For a start -- providing the details of a few typical reads in the first and second case would allow us to make some more specific suggestions.

**Comment by ray1919** [comment]
Yes, it is a amlplicon based data. Thank you for your suggestion. I would give a try of the Pisces, and compare the results.

I subset the bam file with this amplicon region, and enclose the bam file below

[alignment_bam.zip](https://github.com/Illumina/strelka/files/1981908/alignment_bam.zip)

**Comment by ray1919** [comment]
I found after I cut the primers in read pairs, the reads get shorter, and get smaller MAPping Quality in SAM file, the MAPping Quality > 40 decread dramatically.

I used the minimap2 aligner(the original reads is 150bp long). It produce only 40-50bp reads after I trimmed the primers & adapters. So I guess the problem is I choosed a wrong aligner.

**Comment by ctsa** [comment]
Thanks for the followup. Yes, minimap2 is recommended for 100 bases and higher (for instance, in the preprint abstract: https://arxiv.org/abs/1708.01492). I will still try to take a quick look at your example.
