### ISSUE TITLE
Different results after upgrading from Strelka2.7.1 to 2.9.2

### ISSUE THREAD

**Issue by makarov-mskcc** [Illumina/strelka#48]
Dear developers,

After I upgraded from Strelka2.7.1 to 2.9.2 (via conda), I am getting quite different somatic calls for INDELS. Even though total number is close (200 vs 217), only 14 overlap when I compare coordinates. I also checked configureStrelkaSomaticWorkflow files, they are identical, with only difference that 2.9.2 has "maxIndelSize = 49" parameter.

What can de the reason of that?

Thank you

Vlad

**Comment by ctsa** [comment]
Thanks Vlad, I think we're following up on the same item by email so I'll close the issue.

**Comment by makarov-mskcc** [comment]
Hi Chris,
Yes, thank you. I will send you  IGV images for comparison shortly
Vlad

**Comment by EvaPang2022** [comment]
Hi @makarov-mskcc @ctsa, may I know what contributes to the difference here?

Thanks!
