### ISSUE TITLE
Can strelka call somatic variants for specified regions?

### ISSUE THREAD

**Issue by zyywmy** [Illumina/strelka#5]
Can I pass a bed file to strelka to do somatic calling for specified regions? For WGS calling, we want to do divide-and-conquer to call different regions in parallel.
Thanks,

**Comment by ctsa** [comment]
Strelka already does parallelized analysis of different regions.  If you need it for some other purpose, restricting calling to a BED file is in the upcoming 2.8.0 release -- which should be out in a few weeks.

**Comment by ctsa** [comment]
Please see the new `--callRegions` option in the strelka 2.8.2 release here: https://github.com/Illumina/strelka/releases/tag/v2.8.2
