### ISSUE TITLE
FATAL_ERROR: Attempting to lookup basecall quality score 72 which exceeds the maximum cached basecall quality score of 70

### ISSUE THREAD

**Issue by komalsrathi** [Illumina/strelka#50]
Hi,

I am running Strelka on RNA-seq data. I have had no problems running it before but for this particular dataset, it is throwing an error. Here is my command line:

```
configureStrelkaGermlineWorkflow.py --bam=sample.sorted.deduped.bam --referenceFasta=Homo_sapiens_assembly19.fasta --rna --runDir=outdir

outdir/runWorkflow.py -m local -j 8
```

Here are the bam, fasta files as well as the resulting output directory: s3://strelka-test

Please let me know if you need more information.

Thanks
Komal

**Comment by sangtaekim** [comment]
Thanks Komal for the report. It looks like the files in S3 are now downloadable. Can you change the permissions?

**Comment by komalsrathi** [comment]
Hi - Can you try again?

**Comment by sangtaekim** [comment]
It works now. Thanks!

**Comment by sangtaekim** [comment]
It seems that there are alignments with basecall quality values > 70 which trigger a runtime error (https://github.com/Illumina/strelka/tree/master/docs/userGuide#alignment-files). Please refer to this old (but still valid) thread: https://groups.google.com/forum/#!topic/strelka-discuss/GtFMv0vYErg.

**Comment by komalsrathi** [comment]
So either I will have to realign the bams or reset the value MAX_QSCORE in “strelka/ lib/blt_util/qscore_cache.hh” @ line:  “  enum { MAX_QSCORE = 70”, and recompile?
```

**Comment by sangtaekim** [comment]
One way is to convert the fastqs from the "Phred+64" format to the "Phred+33" format, realign the reads and re-run Strelka. Another way is as you said to change MAX_QSCORE and recompile Strelka; but this may create extra false positive calls.

**Comment by komalsrathi** [comment]
Yes this is urgent so I would try the second method first. Like I said in my previous comment, I am unable to find the qscore_cache.hh script so how do I change the MAX_QSCORE?

**Comment by sangtaekim** [comment]
It's at src/c++/lib/blt_util/qscore_cache.hh (https://github.com/Illumina/strelka/blob/master/src/c%2B%2B/lib/blt_util/qscore_cache.hh#L66). The latest Strelka source code is at https://github.com/Illumina/strelka/archive/v2.9.4.zip.

**Comment by sangtaekim** [comment]
Here's the instruction for building Strelka from source: https://github.com/Illumina/strelka/blob/master/docs/userGuide/installation.md.

**Comment by komalsrathi** [comment]
Oh is it weird that I did not have this script and was still able to run strelka on wes and rnaseq data? This is the one that I have: `strelka-2.9.2.centos6_x86_64`.

**Comment by sangtaekim** [comment]
strelka-2.9.2.centos6_x86_64 is a binary release not including source files. Please use the updated link above. Thanks!

**Comment by ctsa** [comment]
Hi @komalsrathi - I'd like to emphasize that if you're using an incorrect basecall quality offset your BAMs are not valid -- if you run these through any somatic calling tool you will be very likely to get a high number of false positive somatic SNV predictions, because each basecall will be associated with an incorrectly elevated quality value. I would recommend fixing the basecall qualities in your fastqs.

**Comment by komalsrathi** [comment]
I understand and totally agree. However, we actually just want to validate a few variants in RNA that we have already identified using DNA analysis - which is why I am not worried about false positives for this specific analysis.

**Comment by komalsrathi** [comment]
Hi - 

I am still facing the same error:

I have installed the new version from source and changed the MAX_QSORE value in qscore_cache.hh:

```
[rathik@reslndbhisbox01 blt_util]$ pwd
/mnt/isilon/maris_lab/target_nbl_ngs/shared_resources/apps/strelka-2.9.4.release_src/src/c++/lib/blt_util

# changed MAX_QSCORE from 70 to 72
[rathik@reslndbhisbox01 blt_util]$ grep MAX qscore_cache.hh 
    enum { MAX_QSCORE = 72,
           MAX_MAP = 90
        if (qscore > MAX_QSCORE) high_qscore_error(qscore,label);
        if (mapping_qscore>MAX_MAP)
            mapping_qscore=MAX_MAP;
    std::array<double,MAX_QSCORE+1> q2p;
    std::array<double,MAX_QSCORE+1> q2lncompe;
    std::array<double,MAX_QSCORE+1> q2lne;
    uint8_t mappedq[MAX_MAP+1][MAX_QSCORE+1];
```

Still getting the same error - see logs here: 
[strelka_logs.txt](https://github.com/Illumina/strelka/files/2120069/strelka_logs.txt)

**Comment by komalsrathi** [comment]
Sorry for my oversight - it works so I am closing this now. Thank you!

**Comment by sangtaekim** [comment]
Glad that it worked. Actually, I was able to run it on both of your data successfully.
