### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by colindaven** [Illumina/strelka#54]
Hi,

correct me if I'm wrong, but Strelka seems to solely support Python2.

Given that Python2 has an end of life in 2020, will Strelka be converted to Python3 ?

Thanks for your time and efforts.
Colin

**Comment by ctsa** [comment]
Hi Colin, Good question. The limiting factor on a python3 update is pyflow, the python task scheduler shared by strelka, manta and few other projects. I imagine we will be more likely to replace the pyflow multi-process scheduling scheme with a pure c++ single-process multi-thread scheme in that timeframe. If that doesn't happen a python3 update might be possible, but is not currently planned.

**Comment by alanhoyle** [comment]
The Python 2 EoL is[ less than 3 months away](https://pythonclock.org): January 1, 2020.  Is there any movement towards futureproofing this?
