### ISSUE TITLE
Difference between strelka2 and strelka1

### ISSUE THREAD

**Issue by zyywmy** [Illumina/strelka#6]
We've just run strelka2 over the Dream challenge WGS datasets. I found if using "PASS" as the filter, the numbers of SNVs are far less than that from strelka1. E.g, Strelka2 only return 427 SNVs for Dream dataset1 while Strelka1 returns 5573. I run Manta first and then run Strelka2 as you mentioned in the user guide. 
Thanks,

**Comment by ctsa** [comment]
This isn't consistent with what we see in general (though not looking at DREAM for performance metrics). If you point to a specific public BAM we might be able to provide some help.

**Comment by zyywmy** [comment]
Sorry for the question. I realized that some errors happened when I passed the BAM files to the command line.  Thanks!
