### ISSUE TITLE
Inconsistant depth of result 

### ISSUE THREAD

**Issue by ray1919** [Illumina/strelka#62]
I use strelka 2.9.7 to call given SNPs in targeted amplicons in human genome. The alignments on position chr10:94942309 for example are more than 7000, however, the vcf resulted in DP of 10.

```
samtools depth -r chr10:94942300-94942310 JX3543.aligned.sorted.bam
chr10   94942300        8001
chr10   94942301        8001
chr10   94942302        7562
chr10   94942303        7562
chr10   94942304        7562
chr10   94942305        7562
chr10   94942306        7561
chr10   94942307        7553
chr10   94942308        7554
chr10   94942309        7554
chr10   94942310        7554

```

output variant.vcf
```
chr10   94942309        .       G       .       .       LowGQX;NoPassedVariantGTs  SNVHPOL=5;MQ=1   GT:GQ:GQX:DP:DPF:FT     0/0:10:10:4:0:LowGQX
```

I was quite confused, all available file are attachd, command is invoked as:

```
configureStrelkaGermlineWorkflow.py --targeted \
--referenceFasta Homo_sapiens_assembly38.fasta \
--callRegions insert.bed.gz \
--forcedGT rs.vcf.gz \
--bam JX3543.aligned.sorted.bam \
--runDir strelka_debug_e \
--region chr10:94942279-94942334
```

[attachment.tar.gz](https://github.com/Illumina/strelka/files/2295905/attachment.tar.gz)

**Comment by sangtaekim** [comment]
On chr10:94942309, most of the reads have MAPQ 0. In Strelka, reads with MAPQ < 20 are not reflected in calculating DP.

**Comment by ray1919** [comment]
I have cut adapters and primer sequences from reads, so the actual insert is about 30 ~ 70 bp long. So the minimap2 aligner gave very low MAPQ. What you would suggest I should do in this situation?

**Comment by ctsa** [comment]
This might be out of strelka's scope. Probably best not to use minimap for reads below ~100 bases.
