### ISSUE TITLE
Strict matching between FASTA and BAM can be problematic

### ISSUE THREAD

**Issue by tdelhomme** [Illumina/strelka#66]
Hi all,

It seems that strelka2 does not want to process a BAM file if a particular chromosome is defined in the header of the BAM file but not in the FASTA reference file.

I have a BAM that contains only TP53 mutation (extract with 'samtools view') and a reference file for chromosome 17 only, files can be found here: https://github.com/IARCbioinfo/data_test/BAM/NA06984_N.bam
https://github.com/IARCbioinfo/data_test/REF/17.fasta

Here is my command:
```
/configureStrelkaGermlineWorkflow.py --bam NA06984_N.bam --referenceFasta 17.fasta   --callRegions TP53_small.bed.gz --runDir strelkaGermline/sample1
```
and the error I get:
```
  Reference genome mismatch: Reference fasta file is missing a chromosome found in the Input BAM/CRAM file: '1'
```

I did not have any variant in the chromosome 1, however it is defined in the header, is this the problem?

Thanks!

**Comment by ctsa** [comment]
Yes, samtools preserves the original header encoding the original reference genome used to align the full BAM. If you use samtools to select a region of the genome, you should still use the original reference genome fasta file using for read mapping.

I understand this requirement can be inconvenient, but many trickier problems would be introduced by loosening the required match between the read mappings and the reference genome.

**Comment by tdelhomme** [comment]
@ctsa I agree, this is not really a bug but more a proposed alternative "improvement", and yes I also think finally that the general practice should be to use same ref than the one used for alignment. Thanks for your response!
