### ISSUE TITLE
Only got very few SNVs using Strelka2

### ISSUE THREAD

**Issue by fredsamhaak** [Illumina/strelka#71]
Hi, 

I simply run Strelka2 using StrelkaGermlineWorkflow on a single sample (whole blood tissue from Human, total bases: 2.19G, average depth: 82.03×) in a 10Mbp target region and it takes nearly 14min (No ERROR info). But I got only 3.9k SNVs while 28.5k SNVs can be found using BWA-SAMTOOLS pipeline (Two pipelines use the same *.sorted.rmdup.bam file). This really makes me confused.

My command lines are as follows:

/home/shenhe/software/strelka-2.9.2.centos6_x86_64/bin/configureStrelkaGermlineWorkflow.py \
--bam out.HiSeqX101700034-CTCAATGA_HCKVKCCXY_L3.sorted.rmdup.bam \
--ref ../00.ref/ucsc.hg19.mhc.fasta \
--callRegions 10Mbed.gz \
--runDir 02.onermdupsample_10Mbed_germline/

02.onermdupsample_10Mbed_germline/runWorkflow.py -m local -j 16

To see how many SNVs they share, I do a statistical analysis and the results are: 

![image](https://user-images.githubusercontent.com/18003589/46256158-666a7400-c4d9-11e8-9be1-fa8e50c9e87d.png)

We can see that most of the SNVs called by Strelka2 can be found by BWA-SAMTOOLS pipeline. But still, Strelka2 can only get very few SNVs.

Am I doing something wrong here? Thank you very much!

All the best!
Fredsamhaak

**Comment by sangtaekim** [comment]
For targeted sequencing data, we recommend to add --targeted in the command line. Can you try adding it?

**Comment by fredsamhaak** [comment]
Really sorry for the late response.

I add --targeted in the command line and it seems that the StrelkaGermlineWorkflow for single sample is doing good this time! Here is the result: 

![image](https://user-images.githubusercontent.com/18003589/46590776-a38dc200-cae8-11e8-8d7e-f0d3e3b53119.png)

I reread the Strelka User Guide in Github and find that adding --targeted parameter is much better for target region analysis (non-WGS cases) because it makes Strelka2 get appropriate depth filtration behavior. Does it result in more 'PASS' SNVs instead of 'LowDepth' ones because regions to be analysed shrink when adding --targeted in the command line? But '--callRegions 10Mbed.gz' parameter has been added to specify the region we want to analyse?

I'll try adding this parameter in the multi-sample pipeline to see if it works too.

Thanks again!

**Comment by sangtaekim** [comment]
Glad to hear that it works now. The LowDepth filter is applied when the depth is very low (less than 2). The depth filter for WGS is mostly for filtering out calls in unusually high depth regions.

**Comment by fredsamhaak** [comment]
Thank you @sangtaekim.

I got it but still, why should I add '**--targeted**' because regions we want to analyse has been specified through adding '**--callRegions** *bed.gz' parameter. Is it about the algorithms in the scripts?

In addition, I do the statistical analysis again and the results are as follows: 

![image](https://user-images.githubusercontent.com/18003589/46644687-0304d400-cbb4-11e8-8c8f-3f260861ec31.png)

We can see that Strelka2 pipeline share most of the SNVs with both BWA-SAMTOOLS and GATK pipeline in this sample.

What's more, most of the SNVs are the same in Single and Multi-sample pipeline in StrelkaGermlineWorkflow, as can be seen from the results below: 

![image](https://user-images.githubusercontent.com/18003589/46645013-5fb4be80-cbb5-11e8-8a01-56482719db02.png)

All the best, 
Fredsamhaak

**Comment by sangtaekim** [comment]
Thanks for sharing the results! 

'--targeted' is used simply to specify the data type (targeted, whole exome or whole genome). In contrast, '--callRegions' is for restricting variant calling to a subset of the region, and can be used regardless of the data type. E.g. we recommend to add '--callRegions *.bed.gz' for whole genome data if the reference includes many short decoys (https://github.com/Illumina/strelka/blob/master/docs/userGuide/README.md#improving-runtime-for-references-with-many-short-contigs-such-as-grch38).

**Comment by fredsamhaak** [comment]
Thanks for your detailed explanation!

Now I know that Strelka2 distinguishes three types of data (targeted, whole exome and whole genome) through the data type parameter we add. But actually, these data are essentially the same (e.g. HiSeq2500 PE150). So why should we tell Strelka2 the data type? Does it (--targeted, --exome...) have an influence on **"depth counting"** on each site? 

Looking forward to hearing from you.

All the best, 
Fredsamhaak

**Comment by sangtaekim** [comment]
Strelka germline caller uses different variant filtering strategies for WGS and non-WGS data. For WGS, Strelka is set to filter out variants with high depths (e.g. greater than ~3x of the chromosome mean) to exclude calls in pericentrometic and other difficult regions. Also, it has an empirical variant scoring (EVS) model that is trained only for WGS. When --targeted or --exome is specified, both the high depth filter and the EVS are disabled.

Best,

Sangtae

**Comment by fredsamhaak** [comment]
I fully understand now! Thank you very much Sangtae!

All the best, 
Fredsamhaak

**Comment by sangtaekim** [comment]
Thanks @fredsamhaak for the great discussion. I'm closing this ticket.
