### ISSUE TITLE
Genotype field is missing in VCF file

### ISSUE THREAD

**Issue by LeeNicha** [Illumina/strelka#73]
Hi

I want GT field in VCF file to find haplotype sequence, but the VCF didn't show GT field.

I typed this below command:

python configureStrelkaSomaticWorkflow.py --normalBam case4_normal.bam --tumorBam case4_tumor.bam --ref Homo_sapiens_assembly38.fasta --runDir strelka_case4

python runWorkflow.py -m local -j 20 

[case4.strelka.vcf.zip](https://github.com/Illumina/strelka/files/2543044/case4.strelka.vcf.zip)

Could you help me, please?
Thank you in advance.

**Comment by sangtaekim** [comment]
Hi @LeeNicha, Strelka does not provide the GT field in somatic calling output. Please refer to https://github.com/Illumina/strelka/issues/16 for a discussion on this topic. Unfortunately, we currently don't have a plan to change the output format.

**Comment by sangtaekim** [comment]
I'm closing this ticket. Please submit another issue if you have other questions regarding this.
