### ISSUE TITLE
genotype likelihoods (PL) for reference calls with --forcedGT

### ISSUE THREAD

**Issue by gmagoon** [Illumina/strelka#75]
It seems that with the --forcedGT option, for cases with reference calls, the ALT allele(s) for SNPs aren't carried over to the output, and genotype likelihoods (PL) are not reported, e.g.:
```
X	70396832	.	A	.	.	PASS	SNVHPOL=3;MQ=60	GT:GQ:GQX:DP:DPF:FT	0/0:15:15:6:0:PASS
```
Is there a way to have these included in the output?
Thanks very much in advance,
Greg

**Comment by sangtaekim** [comment]
Yes, that's the current behavior for SNVs (https://git.illumina.com/Bioinformatics/strelkadev/blob/develop/docs/userGuide/README.md#forced-genotypes). Currently, there is no way for Strelka to include ALT alleles in the output.

**Comment by gmagoon** [comment]
I see, thanks @sangtaekim ...I must have glossed over that on my initial readings of that section
