### ISSUE TITLE
minimum mapping quality for variant calls?

### ISSUE THREAD

**Issue by RichardCorbett** [Illumina/strelka#77]
Hi folks,
Is there a minimum mapping quality required at a location to generate a variant call, or will any aligned reads be used?

**Comment by sangtaekim** [comment]
Reads with MAPQ 20 or higher are used in all aspects of variant calling. The rest of the reads are used in more restricted contexts, e.g. for verifying somatic calls and calculating depth metrics. For details, please refer to the Strelka method documentation (https://github.com/Illumina/strelka/blob/v2.9.x/docs/methods/primary/methods.tex#L301).

**Comment by RichardCorbett** [comment]
Brilliant. Thanks!
