### ISSUE TITLE
Intermediate VCF file availability

### ISSUE THREAD

**Issue by anands-repo** [Illumina/strelka#78]
Hello!

Is there an intermediate VCF or some sort of list of candidate alleles available after the "Read realignment and variant probability inference" step or thereabouts as described in the https://www.biorxiv.org/content/biorxiv/early/2017/09/25/192872.full.pdf? I am looking into some candidate allele statistics. If a tool hack is needed, it would be great if you could point me to a code region to look at.

Thanks!

**Comment by sangtaekim** [comment]
Hi @DiableJambe ,

Sorry for the delay. 

All the candidate alleles are recorded in the VCF output. The "4. Empirical scoring and filtration" step only re-scores variants and applies a passing filter accordingly. The number of records are not changed by the step 4.

Best,

Sangtae

**Comment by anands-repo** [comment]
Hi Sangtae,

Thanks for the response.

Best,
Anand
