### ISSUE TITLE
SomaticEVS threshold

### ISSUE THREAD

**Issue by JunyanZH6** [Illumina/strelka#79]
I found strelka google group maybe inactive. So I post my question here again.

I use Strelka v2.9.7 to call somatic variants and have a question about EVS model. 
Variants are filtered by SomaticEVS value labeled with ‘PASS’ or LOWEVS. 
What is the value of the SomaticEVS threshold?  By default, the threshold is fixed or varied according to real sample data?

Thanks a lot.

**Comment by sangtaekim** [comment]
Hi @JunyanZH6 ,

The SomaticEVS thresholds are 6 for indels and 7 for SNVs. You can find them by searching the "FilterCutoff" value at https://github.com/Illumina/strelka/blob/v2.9.x/src/config/empiricalVariantScoring/models/somaticIndelScoringModels.json and https://github.com/Illumina/strelka/blob/v2.9.x/src/config/empiricalVariantScoring/models/somaticSNVScoringModels.json.

The same thresholds are applied to all input data of the same type (e.g. WGS, WES, germline, paired).  But the thresholds may be different for different versions of Strelka.

Best,

Sangtae
