### ISSUE TITLE
'force' call for every position in provided bed file

### ISSUE THREAD

**Issue by chrausch** [Illumina/strelka#8]
For a gene panel (regions available as bed file) we know all mutated positions (ground truth dataset).  
I'd like strelka to call all positions so that i can develop my own filter that optimizes sensitivity and specificity. Is that already possible? I'm not sure if it can be achieved with the option forceGT.
Thanks for helping!
Regards, Christian

**Comment by ctsa** [comment]
The `--forcedGT` option only serves an allele-specific purpose for indels right now. Every indel allele provided in the forcedGT input will be genotyped and reported. SNVs included in forcedGT VCFs only ensure that the corresponding site will not be block compressed in homozygous reference regions (germline), or ensure that the site will appear in the somatic SNV output (somatic), but will not give any privileged status to the listed SNV alleles. The feature is summarized here:

https://github.com/Illumina/strelka/blob/master/docs/userGuide/README.md#forced-genotypes

For the germline workflow only, it may be somewhat more convenient to suppress homozygous reference region blocking for large regions by using the `--noCompress` option.
