### ISSUE TITLE
Extreme runtime and no results for somatic T/N WGS calling using Strelka

### ISSUE THREAD

**Issue by rxliu** [Illumina/strelka#80]
Hi I am having difficulty using Strelka for WGS somatic variant calling with 2 ~40x coverage TCGA T/N samples. The reference I used is: ftp://ftp.ncbi.nlm.nih.gov/sra/reports/Assembly/GRCh37-HG19_Broad_variant/Homo_sapiens_assembly19.fasta

runWorkflow.py was generated with 

./configureStrelkaSomaticWorkflow.py --ref ~/chrs/HG19_Broad_variant.fa \
--normalBam G39020.TCGA-CG-5730-11A-01D-1600-08.1.bam \
--tumorBam G39020.TCGA-CG-5730-01A-11D-1600-08.1.bam \
--runDir out_strelka_1

and executed as:
./runWorkflow.py -m local -j 24

I ran the workflow on a 24 core node with a 72 hour allocation but it timed out with no output and no files in the workspace or results folder. I was under the impression that interrupted runs would save some output to these directories to be resumed.

I did not include indel candidates from Manta because I had similar issues from Manta, which used the same inputs but timed out after a 24h allocation on 24 cores. The 2015 paper had .3-4 hour runs for Manta on 50x coverage of NA12878. 

This leads me to think there must be something peculiar with my configuration or data? I'd appreciate any insight to this problem

**Comment by sangtaekim** [comment]
Hi @rxliu ,

Thanks for the report. For 80x tumor and 40x normal data, the runtime on our system with 20 cores is around 2 hours. Answers to the following questions would be helpful to pin down the problem. 

- Is the "workspace" folder completely empty? 
- Did you monitor the CPU usage after running Strelka? If yes, what was the CPU usage after ~10 mins and after ~5 hours?
- Did Strelka run on any other data?

Sangtae

**Comment by rxliu** [comment]
Hi @sangtaekim,

Since the original post I have tried two other sample pairs of similar coverage to the first, and had the same issue with 72h timeouts with empty workspaces. The "workspace" folder is entirely empty in all samples for which it was run. 

I did not monitor the CPU usage, but I will try again while monitoring and update this post afterward. Thanks!

**Comment by sangtaekim** [comment]
Thanks for the reply. Strelka stores temporary results and log files at the workspace folder. An empty workspace often indicates that there are issues in the system. Can you check whether you can successfully run the somatic demo (https://github.com/Illumina/strelka/blob/v2.9.x/docs/userGuide/quickStart.md#installation)? Also, can you run Strelka on the demo data using the commands that you used for the TCGA data? The demo data is at ${STRELKA_INSTALL_PATH}/share/demo/strelka/data. What is the Strelka version that you are using?

**Comment by rxliu** [comment]
Hi @sangtaekim , the demo ran successfully and found no differences when I first installed it, and I ran it again just now and it found no differences again. I am using version 2.9.10.centos6_x86_64

Actually, when testing interactively on a compute node, ater attempting to keyboard interrupt the ./runWorkflow command because I had wanted to adjust the jobs setting, I saw that the [pyFlow run was only just initiated](https://photos.app.goo.gl/sJeTKez4o1Kgcwk3A), and I suppose everything was stalled for some reason until then.

For all previous runs I found it strange that the slurm out file was entirely blank, while the demo originally had output detailing the workflow, tasks launching etc.


I was able to replicate this with the other samples that I had tried as well, when run from a compute node. However, when run from a login node (non-compute) the pyFlow is immediately initiated. I am not sure what is responsible for this discrepancy, but I am glad to have made some headway on this problem.

**Comment by sangtaekim** [comment]
Glad to hear that you got a clue. Please report report back if you find a problem in Strelka or pyflow.

**Comment by rxliu** [comment]
@sangtaekim Thank you, will do. I was wondering if you had any suggestions as to what might be responsible for this strange behavior. It seems really bizarre to me but the same behavior occurs with Manta as well, which has a similar process of creating a runWorkflow.py file, and I'm having difficulty finding anyone else who has experienced such a thing

**Comment by ctsa** [comment]
@rxliu - The workspace directory should at the very least contain the  pyflow.data/ subdirectory if ./runWorkflow.py has actually started. From the comments above it sounds like this is not the case. Could this be a slurm or OS issue? It sounds from your description above like the runWorkflow.py process is only able to start once the interrupt signal is sent. Perhaps you could try making the run command more explicit by changing it to `python runWorkflow.py -m local -j 24`?

**Comment by rxliu** [comment]
Right, the workspace is completely empty. I figured out that the problem was in get_run_options, where
> smtplib.SMTP('localhost')

stalled indefinitely when run on a compute node, but not a login node.  Since I don't plan on using the email option, I have changed /lib/python/makeRunScript.py to disable this. Thanks again for the help!

**Comment by ctsa** [comment]
Thanks for the report, we haven't previously encountered a hang there but it certainly makes sense, I will link this as a pyflow bug.

**Comment by arkal** [comment]
FWIW if someone sees this and doesn't care about email reports, 
```
sed -i s/"isEmail = isLocalSmtp()"/"isEmail = False"/g ${RUNDIR}/runWorkflow.py 
```
works great!
