### ISSUE TITLE
TAR field

### ISSUE THREAD

**Issue by mozack** [Illumina/strelka#81]
Hi,

The documentation appears to indicate that the TAR field contains rerefence counts:

```
Somatic indels:
tier1RefCounts = First comma-delimited value from FORMAT/TAR
tier1AltCounts = First comma-delimited value from FORMAT/TIR
Somatic allele freqeuncy is $tier1AltCounts / ($tier1AltCounts + $tier1RefCounts)
```

However, the VCF header indicates the following:
```
##FORMAT=<ID=TAR,Number=2,Type=Integer,Description="Reads strongly supporting alternate allele for tiers 1,2">
```

Can you please clarify?

Thanks!

**Comment by sangtaekim** [comment]
Hi @mozack ,

The TAR field reports the #reads strongly supports **any allele other than the indel allele**. In the majority of cases, it will simply be the reference counts, but if there exist multiple alt alleles, it will be the sum of the read counts supporting the alleles other than the "ALT" allele.

Best,

Sangtae

**Comment by mozack** [comment]
OK, thanks.
