### ISSUE TITLE
How could avoid contamination model？

### ISSUE THREAD

**Issue by ggoodstudydaydayup** [Illumina/strelka#83]
Hi,
    I was wondering that if I avoid the contamination model, the somatic mutation will be homozygosis in normal and heterozygosis in tumor？ Cause I'm not sure why there were all heterozygosis in tumor and normal.
![image](https://user-images.githubusercontent.com/46480129/50820386-7363f280-1367-11e9-8eba-15dff29da76f.png)
I would really appreciate your advice on this.

**Comment by sangtaekim** [comment]
You can adjust the contamination tolerance parameters at ${STRELKA_INSTALL_PATH}/bin/configureStrelkaSomaticWorkflow.py.ini. 

```
#
# Tolerance of tumor contamination in the normal sample
# Allowed range: [0-1]
# 
ssnvContamTolerance = 0.15
indelContamTolerance = 0.15
```

If you change ssnvContamTolerance (tolerance for SNVs) and indelContamTolerance (tolerance for indels) to 0, Strelka will become less tolerant to contamination in the normal sample.

**Comment by ggoodstudydaydayup** [comment]
Thank you for your help

**Comment by sangtaekim** [comment]
You're welcome.
