### ISSUE TITLE
Version 2.8.0 as in Illumina Tumor app 5.0 is required

### ISSUE THREAD

**Issue by mortunco** [Illumina/strelka#84]
Hi,

Is there anyway I can reach version 2.8.0 as I stated in the title ? We are working on a project where we have multiple tumor WGS from different callers so trying to set a standard in mutation calling.

Thank you very much for the help, 

(bioconda has 2.8.2)

Best regards,

Tunc.

**Comment by sangtaekim** [comment]
You can access the 2.8.0 release at https://github.com/Illumina/strelka/releases/tag/v2.8.0. I've just attached a binary distribution for 64-bit linux that was missing in this release.
