### ISSUE TITLE
SmallAssembler vs IterativeAssembler

### ISSUE THREAD

**Issue by anands-repo** [Illumina/strelka#85]
There seem to be two versions of assemblers in the repository in strelka/src/c++/lib/assembly.

The iterative assembler seems to check cyclic k-mers before assembly, but the small assembler seems to wait till it finds a repeat within a given contig itself. I am not sure whether there are other differences. Is one of the versions preferred? The documentation seems to point to the use of iterative assembler because it mentions cyclic k-mer checks.

**Comment by x-chen** [comment]
The iterative assembler is preferred. It has the advantage to assemble through low-complexity regions with low coverage and has shown better performance over the other.

**Comment by sangtaekim** [comment]
Yes, Strelka uses only the iterative assembler.

**Comment by ggoodstudydaydayup** [comment]
Hi, could I use the the small assembler with iterative assembler together?

**Comment by sangtaekim** [comment]
Why and how do you plan to use both?

**Comment by anands-repo** [comment]
Thank you Xiaoyu and Sangtae.

-Anand

**Comment by sangtaekim** [comment]
You're welcome.

**Comment by ggoodstudydaydayup** [comment]
Because there are many high-complexity region. Could I divide the low and high-complexity region? And use different assembler respectively?

**Comment by sangtaekim** [comment]
For high-complexity region, the iterative asseembler will finish quickly when k is small, and there wouldn't be a real benefit of complicating the logic.

**Comment by ggoodstudydaydayup** [comment]
I truly appreciate your timely help
