### ISSUE TITLE
the question of MAPQ

### ISSUE THREAD

**Issue by ggoodstudydaydayup** [Illumina/strelka#86]
Hi,
    I used to check my somatic snvs. And I'm not sure about the mean of  threshold for MAPQ.  Does tier1 mean normal ? And tier2 means tumor?
![image](https://user-images.githubusercontent.com/46480129/51170059-6e172280-18e8-11e9-8a24-b4e1889e1af5.png)
    Thanks a lot.

**Comment by sangtaekim** [comment]
The description about tier1 and tier2 is at https://github.com/Illumina/strelka/blob/v2.9.x/docs/methods/primary/methods.tex#L301. In brief, tier1 reads are more reliable reads that are used everywhere in Strelka. Tier2 reads are less reliable and used in limited contexts. The determination of tiers is independent on samples.

**Comment by ggoodstudydaydayup** [comment]
Thank you very much

**Comment by sangtaekim** [comment]
You're welcome.
