### ISSUE TITLE
Which read tier is used to determine PASS

### ISSUE THREAD

**Issue by LukeGoodsell** [Illumina/strelka#87]
Hi,

I would like to know how to determine which tier of reads is used in determining the pass/fail status of each variant. From [the methods](https://github.com/Illumina/strelka/blob/v2.9.x/docs/methods/primary/methods.tex#L301) and the [v1 docs](https://sites.google.com/site/strelkasomaticvariantcaller/home/somatic-variant-output) it seems that whichever tier is listed in the TQSS field was used to determine the quality score. Is this still the case? Is the QSS used to determine the pass/fail status of each variant? Is it the case both when the EVS model or hard filters are used?

Thanks,
Luke

**Comment by sangtaekim** [comment]
Hi @LukeGoodsell, sorry for the delayed response. 

TQSS/TQSS_NT (SNVs) and TQSI/TQSI_NT are still used to indicate the tier used to compute the corresponding QSS/QSS_NT/QSI/QSI_NT scores. But, QSS/QSI is not used to determine pass/fail.

 When EVS is on, the EVS score (SomaticEVS) is used to determine the PASS/LowEVS status. When EVS is off, QSS_NT (SNVs) or QSI_NT (indels) along with NT (normal genotype) are used to determine the PASS or QSS_ref/QSI_ref status. Please refer to the VCF description of the low score filters

EVS is on:
```
##FILTER=<ID=LowEVS,Description="Somatic Empirical Variant Score (SomaticEVS) is below threshold">
```

EVS is off:
```
##FILTER=<ID=QSS_ref,Description="Normal sample is not homozygous ref or ssnv Q-score < 15, ie calls with NT!=ref or QSS_NT < 15">
##FILTER=<ID=QSI_ref,Description="Normal sample is not homozygous ref or sindel Q-score < 40, ie calls with NT!=ref or QSI_NT < 40">

**Comment by LukeGoodsell** [comment]
Thanks, @sangtaekim. So am I correct in understanding that only reads in tier 1 are used for the SomaticEVS calculation?

**Comment by sangtaekim** [comment]
No. QSS_NT/QSI_NT is used for the SomaticEVS calculation, and QSS_NT/QSI_NT may be calculated using both tier 1 and 2 reads.

**Comment by LukeGoodsell** [comment]
Thanks, @sangtaekim. In that case, if I wanted to get the count of reads supporting/not supporting a given variant call, would the most fair method be to identify which read tier was used for QSS_NT/QSI_NT (TQSS_NT/TQSI_NT) and then use the read counts in this tier?

The documentation [here](https://github.com/Illumina/strelka/tree/v2.9.x/docs/userGuide#somatic-variant-allele-frequencies) suggests only using tier 1, but in cases where tier 2 reads were used in determining whether the variant passes, wouldn't it be more accurate to use tier 2?

**Comment by sangtaekim** [comment]
We recommend to use only tier1 read counts to avoid unnecessary complications. For example, even when QSS_NT is calculated using both tier1 and tier2 reads (i.e. TQSS_NT=2), some features used by somatic EVS (e.g. TumorSampleReadPosRankSum) are computed using only tier1 reads. In this case, it's not clear whether we should use both tier1 and tier2 or only tier1 reads for AF calculations.
