### ISSUE TITLE
What is the definition of false positive regions?

### ISSUE THREAD

**Issue by securelsh** [Illumina/strelka#90]
I found "InSilicoMix_falsePositiveRegions.bed.gz" file. In this file, about 2.6 billion bases are marked. (https://figshare.com/articles/Supporting_Data_for_Strelka2_Fast_and_accurate_variant_calling_for_germline_and_somatic_sequencing_applications_/6203264).

**What is the definition of false positive regions?** When i evaluate tools using InSilicoMix data, I don't know whether the regions are considered or not.

Actually, when i evaluate Strelka using the data and false positive regions, Strelka output a result which are similar to results in Strelka paper. However, for except false positive regions, Strelka output a poor result.

**Comment by sangtaekim** [comment]
They are the regions where query-only calls (calls that are not in the truth file) are counted as false positives. Outside of the FP regions, query-only calls are counted as unknown. Conceptually, FP regions are similar to the confident regions in Platinum Genomes or GIAB truth sets. For more details, please refer to the som.py documentation: https://github.com/Illumina/hap.py/blob/master/doc/sompy.md.
