### ISSUE TITLE
Extra Example Desired for Joint Analysis

### ISSUE THREAD

**Issue by DarioS** [Illumina/strelka#91]
The current example code is

```
${STRELKA_INSTALL_PATH}/bin/configureStrelkaGermlineWorkflow.py \
--bam NA12878.cram \
--bam NA12891.cram \
--bam NA12892.cram \
--referenceFasta hg19.fa \
--runDir ${STRELKA_ANALYSIS_PATH}
```

Could an example be added to the user guide that shows how to use all of the BAM files within a particular directory without manually having to specify each one by `--bam`? If I have a BASH array created by

```
NormalAlignmentsFiles=(`find /project/cancer/DNA/mapped/* -name \*_Blood_\*.bam`)
```
what must I do next?

Also, the quick-start guide, unlike the user guide, uses `--ref` instead of `--referenceFasta` which might need to be updated.

**Comment by sangtaekim** [comment]
Hi @DarioS ,

Strelka supports joint germline calling only in small cohorts (most commonly trios or quertets). Thus, we prefer not to provide an easy way to input all the BAM files in a directory which seems more appropriate for larger scale analysis.

Thanks for pointing out the inconsistency of the quick-start and user guide. I'll correct it.

**Comment by DarioS** [comment]
I understand.
