### ISSUE TITLE
Output realigned BAM doesn't output BAM file

### ISSUE THREAD

**Issue by sbgLuka** [Illumina/strelka#92]
Hi, I am using Strelka2 (2.9.10) when I tried to output realigned BAM file. I added that command to config file, here it is: 

`[StrelkaSomatic]
maxIndelSize = 49
depthFilterMultiple = 3.0
snvMaxFilteredBasecallFrac = 0.4
snvMaxSpanningDeletionFrac = 0.75
snvMaxFilteredBasecallFrac = 0.4
snvMaxSpanningDeletionFrac = 0.75
indelMaxWindowFilteredBasecallFrac = 0.3
ssnvPrior = 0.0001
sindelPrior = 0.000001
ssnvNoise = 0.0000005
sindelNoiseFactor = 2.2
ssnvNoiseStrandBiasFrac = 0.0
minTier1Mapq = 20
minTier2Mapq = 0
ssnvQuality_LowerBound = 15
sindelQuality_LowerBound = 40
ssnvContamTolerance = 0.15
indelContamTolerance = 0.15
isWriteRealignedBam = 1`

Tool finished successfully, but there isn't realigned BAM anywhere. There isn't even realigned folder like it says in default config file in comments. Did you withdraw this feature from Strelka2?

**Comment by ctsa** [comment]
The capability is still there, it looks like the bam path description was missing the 'results' directory in the config file. The correct path is:

    ${ANALYSIS_DIR}/results/realigned/realigned.S${SAMPLE_INDEX}.bam

...or for somatic:

    ${ANALYSIS_DIR}/results/realigned/realigned.{normal,tumor}.bam


Updated here: 

https://github.com/Illumina/strelka/commit/d7377443b62319f7c7bd70c241c4b2df3459e29a
