### ISSUE TITLE
Resource Guide

### ISSUE THREAD

**Issue by DarioS** [Illumina/strelka#93]
Could there be an approximate recommendation for estimating the amount of time an analysis will take, to allow easier specification of computing resources on a cluster such as `#PBS -l walltime=4:00:00` for new users? Without any experience, it's hard to guess even close to the desired value.

**Comment by sangtaekim** [comment]
The main page includes the following description:

> Runtime on a 28-core server is ~40 minutes for 40x WGS germline analysis and ~3 hours for a 110x/40x WGS tumor-normal somatic analysis. More details on Strelka2 methods and benchmarking for both germline and somatic calling are described in:
> Kim, S., Scheffler, K. et al. (2018) Strelka2: fast and accurate calling of germline and somatic variants. Nature Methods, 15, 591-594. doi:10.1038/s41592-018-0051-x

The paper contains run times and memory usage on Amazon EC2 nodes for public data.
