### ISSUE TITLE
Permit Input Sample Naming

### ISSUE THREAD

**Issue by DarioS** [Illumina/strelka#94]
Strelka specifies input files in the format `--bam a.bam --bam b.bam --bam c.bam` and, for germline calling, the output files are named based on the order of input with IDs S0, S1, S2. This can get confusing if the analysis is run again, but with an new sample added or an existing sample removed because some output file ID numbers can become slightly different to the previous run of the script. Would allowing corresponding IDs such as `--ID TB96 --ID TB34 --ID TB194` make the interpretation of output file names more robust (as long as the user keeps the two input lists aligned)?

It might also be convenient to permit the addition of a sample ID into the somatic output file names. If the user is doing ten pairs of samples at the same time, they would currently need ten different output directories to avoid overwriting of the output file, since it's fixed to `somatic.snvs.vcf.gz`.

**Comment by sangtaekim** [comment]
We want to keep Strelka command like parameters as simple as possible and thus prefer not to change the output file names. If the default names cause inconvenience for you, please feel free to fork and make your own changes.

**Comment by DarioS** [comment]
I will use Linux's `rename` program after the results are generated and ensure that each sample's results are output to a separate directory.
