### ISSUE TITLE
gVCF error?

### ISSUE THREAD

**Issue by wangshun1121** [Illumina/strelka#97]
I used StrelkaGermlineWorkflow to call variants using RNA seq data. Then I used following commands to check this file:

```
bcftools norm -m +any -O z -o unmarked.vcf.gz NoMarked.vcf.gz
```

this command end up with error, saying:

```
Error at chr1:1040663: cannot combine diploid with haploid genotype
```

Then I went to the position and saw:

```
chr1    1040663 .       A       .       .       LowGQX  .       GT:GQX:DP:DPF:MIN_DP    .:.:0:0:0
chr1    1040663 .       A       AT      230     LowGQX;LowDepth CIGAR=1M1I;RU=T;REFREP=0;IDREP=1;MQ=0   GT:GQ:GQX:DPI:AD:ADF:ADR:FT:PL  1/1:35:4:0:0,13:0,0:0,13:LowGQX;LowDepth:273,38,0
```

is this the error of gVCF file?

**Comment by wangshun1121** [comment]
I think I should use following commands:

```
bcftools norm -m +any -O z -o unmarked.vcf.gz NoMarked.vcf.gz
```

Perhaps such errors are originated from chr-spliting for parallel processing. But I think this point should be corrected.

**Comment by sangtaekim** [comment]
Hi @wangshun1121 , I don't quite get the issue here. Can you clarify?

**Comment by wangshun1121** [comment]
The gVCF file from strelka, I think that same position shouldn't be seen in different lines. Such as the chr1:1040663 above.

**Comment by sangtaekim** [comment]
Thanks for the clarification. The answer at https://github.com/Illumina/strelka/issues/96 applies here too: "Indels use a prefix base, so this is how the caller currently works if there is an adjacent SNV or (in this case), a fragmented gVCF reference block."

**Comment by wangshun1121** [comment]
Thank you for your reply. I checked many gVCFs by strelka2, and found such phenomena can be seen easily. When using GATK tools, such as `GenomicsDBImport` in GATK4, such indel may cause error in GATK. Is there any suggestion to make strelka2's gVCF compatible to GATK? 

P.S: strelka2's gVCFs can be merged using `bcftools merge`. However, too much information lost in merged vcf.  Then is there any other tools can be used for gVCFs merge?

**Comment by wangshun1121** [comment]
Here is the key error info from GATK4 `GenomicDBImport`:

```
terminate called after throwing an instance of 'VCF2TileDBException'
  what():  VCF2TileDBException : Incorrect cell order found - cells must be in column major order. Previous cell: [ 13, 3095677425 ] current cell: [ 13, 3095677425 ].
The most likely cause is unexpected data in the input file:
(a) A VCF file has two lines with the same genomic position
(b) An unsorted CSV file
(c) Malformed VCF file (or malformed index)
See point 2 at: https://github.com/Intel-HLS/GenomicsDB/wiki/Importing-VCF-data-into-GenomicsDB#organizing-your-data
```

**VCF file has two lines with the same genomic position** is the key point! I went to the link above and trying to solve this problem.

**Comment by wangshun1121** [comment]
Suddenly I see [gvcfgenotyper](https://github.com/Illumina/gvcfgenotyper), let me try it!

**Comment by sangtaekim** [comment]
@wangshun1121 , yes, that's the best tool for manipulating Strelka's GVCFs.

**Comment by wangshun1121** [comment]
Almost 3 years since my commission  of this issue! Now we are trying tumor-only somatic mutation detection pipeline. 

Strelka doesn't support tumor-only somatic mutation calling. But we have thousands samples of germline variants detected by strelka. We don't want to re-call these mutation using GATK, and trying to make Panel-of-Normal for Mutect2. 

Then we have to import strelka mutations into GenomeDB for PON production! And I'll try to convert strelka vcf/gvcf files by myself.

It's long time since strelka2's update, perhaps parameter like Mutect2's `-max-mnp-distance` can be added?
