### ISSUE TITLE
strelka2 and tumour only calling

### ISSUE THREAD

**Issue by sbilobram** [Illumina/strelka#98]
Hi all,

Found some very earlier posts about this issue so just  checking that Strelka has NO workflow or tool to find variants with just a tumour sample, (that is without a matched normal.) 
I am running Mutect2 and am trying out Pisces but I would like to know definately that Strelka has no approach to this issue yet.
Can somebody from Strelka or Illumina confirm this?

Thanks

**Comment by sangtaekim** [comment]
Strelka doesn't support tumor-only calling.

Sangtae

**Comment by sbilobram** [comment]
suggestions or recommendations for other tools or platforms?

**Comment by sangtaekim** [comment]
You already mentioned Mutect2 and Pisces. I don't have any other tool in mind.

**Comment by sbilobram** [comment]
Okay thanks.
And how do you know this? Do you know of plans for Strelka to address this?

**Comment by sangtaekim** [comment]
I'm a developer of Strelka. Currently we don't have a plan to support tumor-only calling.

**Comment by kscheffler** [comment]
Illumina does also offer Dragen, which supports tumour-only calling and can be run in the cloud via BaseSpace: https://basespace.illumina.com (or if you purchase a Dragen box). Unfortunately it is not free, because it runs on special-purpose hardware.

**Comment by Dagsbio** [comment]
You can also use VarDict or FreeBayes in tumor-only settings
