### ISSUE TITLE
Unknown error in first step of Strelka

### ISSUE THREAD

**Issue by beginner984** [Illumina/strelka#99]
Hi,

Could you please help me with this error

[fi1d18@cyan01 fi1d18]$ /temp/hgig/fi1d18/strelka-2.9.2.centos6_x86_64/bin/configureStrelkaGermlineWorkflow.py --normalBam /temp/hgig/fi1d18/1631_WTSI-OESO_013_b/mapped_sample/HUMAN_1000Genomes_hs37d5_genomic_WTSI-OESO_013_b.dupmarked.bam --referenceFasta hg38.fa --runDir demo_somatic
Usage: configureStrelkaGermlineWorkflow.py [options]

configureStrelkaGermlineWorkflow.py: error: no such option: --normalBam
[fi1d18@cyan01 fi1d18]$ 

Thanks a lot for any help

**Comment by sangtaekim** [comment]
Hi @beginner984 ,

For somatic calling, please use ``configureStrelkaSomaticWorkflow.py`` instead of ``configureStrelkaGermlineWorkflow.py``. For germline calling, you have to use ``--bam`` instead of ``--normalBam``.

Sangtae

**Comment by beginner984** [comment]
Sorry

Saying 

```

[fi1d18@cyan01 fi1d18]$ /temp/hgig/fi1d18/strelka-2.9.2.centos6_x86_64/bin/configureStrelkaSomaticWorkflow.py --normalBam /temp/hgig/fi1d18/1631_WTSI-OESO_013_b/mapped_sample/HUMAN_1000Genomes_hs37d5_genomic_WTSI-OESO_013_b.dupmarked.bam --tumorBam /temp/hgig/fi1d18/1631_WTSI-OESO_013_b/mapped_sample/HUMAN_1000Genomes_hs37d5_genomic_WTSI-OESO_013_b.dupmarked.bam --referenceFasta hg38.fa --runDir demo_somatic

CONFIGURATION ERROR:
Reference genome mismatch: Reference fasta file is missing a chromosome found in the normal BAM/CRAM file: '1'

[fi1d18@cyan01 fi1d18]$

```

**Comment by sangtaekim** [comment]
You have to provide that same reference fasta that you used to create the BAM files.

**Comment by beginner984** [comment]
Sorry help me please#

I am running this but my results is empty 


[fi1d18@cyan01 fi1d18]$ /temp/hgig/fi1d18/strelka-2.9.2.centos6_x86_64/bin/configureStrelkaSomaticWorkflow.py --normalBam /temp/hgig/fi1d18/1631_WTSI-OESO_013_b/mapped_sample/HUMAN_1000Genomes_hs37d5_genomic_WTSI-OESO_013_b.dupmarked.bam --tumorBam /temp/hgig/fi1d18/1631_WTSI-OESO_005_b/mapped_sample/HUMAN_1000Genomes_hs37d5_genomic_WTSI-OESO_005_b.dupmarked.bam --referenceFasta /temp/hgig/fi1d18/hs37d5.fa --runDir demo_somatic1
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated

Successfully created workflow run script.
To execute the workflow, run the following script and set appropriate options:

/temp/hgig/fi1d18/demo_somatic1/runWorkflow.py
[fi1d18@cyan01 fi1d18]$ /temp/hgig/fi1d18/demo_somatic1/runWorkflow.py
Usage: runWorkflow.py [options]

Version: 2.9.2

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -m MODE, --mode=MODE  select run mode (local|sge)
  -q QUEUE, --queue=QUEUE
                        specify scheduler queue name
  -j JOBS, --jobs=JOBS  number of jobs, must be an integer or 'unlimited'
                        (default: Estimate total cores on this node for local
                        mode, 128 for sge mode)
  -g MEMGB, --memGb=MEMGB
                        gigabytes of memory available to run workflow -- only
                        meaningful in local mode, must be an integer (default:
                        Estimate the total memory for this node for local
                        mode, 'unlimited' for sge mode)
  -d, --dryRun          dryRun workflow code without actually running command-
                        tasks
  --quiet               Don't write any log output to stderr (but still write
                        to workspace/pyflow.data/logs/pyflow_log.txt)
  -e MAILTO, --mailTo=MAILTO
                        send email notification of job completion status to
                        this address (may be provided multiple times for more
                        than one email address)

  development debug options:
    --rescore           Reset task list to re-run hypothesis generation and
                        scoring without resetting graph generation.

  extended portability options (should not be needed by most users):
    --maxTaskRuntime=hh:mm:ss
                        Specify scheduler max runtime per task, argument is
                        provided to the 'h_rt' resource limit if using SGE (no
                        default)

Note this script can be re-run to continue the workflow run in case of
interruption. Also note that dryRun option has limited utility when
task definition depends on upstream task results -- in this case the
dry run will not cover the full 'live' run task set.

[fi1d18@cyan01 fi1d18]$

Any suggestion please?

**Comment by sangtaekim** [comment]
Did you run 'runWorkflow.py'? Please refer to https://github.com/Illumina/strelka/blob/v2.9.x/docs/userGuide/quickStart.md.

**Comment by beginner984** [comment]
Sorry how I run 'runWorkflow.py' please? In terminal (path) I just typed 'runWorkflow.py' and pressed ENTER but results files is empty, I am not sure how to run 'runWorkflow.py'

**Comment by beginner984** [comment]
Thanks a lot for helping me, now program running

**Comment by beginner984** [comment]
Sorry, since my last comment program is running, any way for speeding the process please?

**Comment by sangtaekim** [comment]
The runtime varies by the data and the system. If there is a reason to believe that it's much slower than what we reported in the GitHub page or in the paper, please report back.

**Comment by beginner984** [comment]
Thanks a lot for reading my concerns; finally finished; RESULTS file (variants) is empty. I have attached my error file, could you please help me solving these errors?

https://www.dropbox.com/s/npvgkh2i2wd48qm/COLO.txt?dl=0

**Comment by sangtaekim** [comment]
The error message says that your BAM file is likely to be corrupted.

**Comment by beginner984** [comment]
Sorry I just tried with another pair of my .bam files but now in spite of previous trial I finished with ATTACHED errors in minutes

https://www.dropbox.com/s/d9ldst5d3qf0z50/COLO.txt?dl=0

Could you please look? So you think my samples are corrupted? I have not removed the marked duplicates is it possible that errors come from that?

I am sorry to sparing your time a lot

**Comment by beginner984** [comment]
Sorry another possible reason for failing to run your software comes to mind is this: I don't have matched normal samples instead for each patient I have cancer and cancer derived model (organoid) and goal would be calling variants in cancer and organoid to see if genetic alterations in organoids recapitulating variants in cancer, I am not quite sure if that matters that I don't have matched normal

**Comment by sangtaekim** [comment]
Still it is likely to be because of the BAM file. Please check your input BAM files are valid.

**Comment by beginner984** [comment]
Sorry you were right because when I tried with a pair of my RNA-seq .bam files I got results. Sorry please help me in getting intuition from these results; My ultimate goal is seeing whether mutations were
consistent between the tumor and the matched organoid, so I have a .vcf file for SNV and a .vcf file for indel, how I could know for instance CDKN2A has been mutated which samples (I mean cancer, organoid or both to find consistency)

Thank you for any help

**Comment by sangtaekim** [comment]
Strelka somatic caller is designed for tumor/matched-normal sample pairs. I cannot answer questions specific to your experimental setup.

**Comment by beginner984** [comment]
Sorry 

In this paper DOI: 10.1038/s41467-018-05190-9

Authors have called the somatic mutations by Strelka from tumour and derived model and nothing has been mentioned about matched normal sample :(
Page 10 Whole-genome sequencing analysis part

**Comment by sangtaekim** [comment]
One can use Strelka for their specific purpose at one's own discretion. In this case, I would contact the authors of the paper.

**Comment by beginner984** [comment]
Thanks a lot for bearing with me

Sorry hopefully as the latest disturbance in this discussion, can I use strelka for calling somatic copy number alterations in my samples?

Anyway thank you so much for replying me

**Comment by sangtaekim** [comment]
No, Strelka doesn't support copy number alteration calling. Thanks!

**Comment by HyojeenLee** [comment]
Hellp, 
I used in aligning, an indexed version of reference genome (hg39.fa to) hg38.mmi (which was suggested by minimap2 to reduce time),
 then should I use the same .mmi or .fa for the reference in Strelka configuration?
